### ISSUE TITLE
Add PDF Support

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog-doc#1037]
Add PDF support by using rst2pdf

**Comment by rgerhards** [comment]
does that run sphinx generation? I don't think so. Sphinx has it's own support for pdf output.  Usually, it requires LaTex, but this here looks like an appealing alternative:

https://sphinx-simplepdf.readthedocs.io/en/latest/

**Comment by alorbach** [comment]
I will try LaTex first

**Comment by alorbach** [comment]
changes not needed to build with latex.
