### ISSUE TITLE
Doc build process - Warning because of the html theme

### ISSUE THREAD

**Issue by teifler** [rsyslog/rsyslog-doc#150]
You receive a warning messages because of the html theme if you build the doc!

Here you can find the warning message: 
WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.

**Comment by deoren** [comment]
I haven't seen this error with recent doc builds. Will go ahead and close this, but please sound off if you still experience the issue.
