### ISSUE TITLE
 wrong link in /doc/master/configuration/modules/filters.html

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog-doc#166]
"/doc/master/configuration/expression.html" does not exist and is is referenced by:
/doc/master/configuration/filters.html

**Comment by mostolog** [comment]
_Compiled_ documentation at http://www.rsyslog.com/doc/master/configuration/filters.html properly links to http://www.rsyslog.com/doc/master/rainerscript/expressions.html
On the other hand, raw documentation (ie: github .rst)
https://github.com/rsyslog/rsyslog-doc/blob/master/source/configuration/filters.rst is linking https://github.com/rsyslog/rsyslog-doc/blob/master/source/rainerscript/expressions.html and https://github.com/rsyslog/rsyslog-doc/blob/master/source/configuration/property_replacer.html which are a 404 at github.

To be honest, I don't know if using relative paths could solve this issue, but I don't expect linking a .rst to be converted to .html. Will that work @rgerhards ?

**Comment by deoren** [comment]
@mostolog Looks like the `filters.rst` file was using both older reference syntax and was also using hard-coded references to html files. I'll submit a PR for this shortly.
