### ISSUE TITLE
Missing step in build docs

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-doc#180]
from @ariscn posted to wrong issue tracker at https://github.com/rsyslog/rsyslog/issues/540

http://www.rsyslog.com/doc/build_from_repo.html is missing the list of requirements from http://www.rsyslog.com/doc/v7-stable/installation/install_from_source.html

**Comment by mostolog** [comment]
As version 7 is considered deprecated, and with the recent https://github.com/rsyslog/rsyslog/pull/1203 which links building from source rsyslog.com page (I'll try to improve that README.md to have a better on-site explanation), I think you can close this issue.
