### ISSUE TITLE
interlinking problems

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-doc#22]
A user report I received on the web site below. I think it is related to the doc generation process:

I'm not sure if I'm directing this to the right place, but I couldn't find anything for feedback about the web site and this seemed like the best option to send to.

I was looking at the documentation on http://www.rsyslog.com, and got an error trying to follow a link. I was at this page - http://www.rsyslog.com/doc/v7-stable/configuration/modules.html#id2 and I tried to follow the link for omfile under Output Modules (http://www.rsyslog.com/doc/v7-stable/configuration/omfile.html), but I get the error "Invalid file specified". I tried omfwd, omjournal, ompipe, and omusrmsg, and they all get the same error. I also tried imfile under Input Modules, but I get the same error.

I'm on Windows 7, using a Chrome browser. I've tried it under Internet Explorer as well, but get the same results.

I do like the new look, it just appears that you have a hiccup here to fix.

**Comment by deoren** [comment]
@rgerhards Is this still an issue, or was it resolved since this issue was originally created? Looking around the v7 and v8 docs briefly, I didn't spot the problems noted above (ignoring the original links of course, as those return 404s).

**Comment by rgerhards** [comment]
I think it is solved. In any case, if there are issues in pre-v8, I would ignore them as these versions are really phased out. So I'll close the issue. If new problems come up, we can always open a new and more concrete one.
