### ISSUE TITLE
Formal Statement of RainerScript

### ISSUE THREAD

**Issue by whm** [rsyslog/rsyslog-doc#28]
A formal definition of the RainerScript syntax will aid in generating valid rsyslog configurations.  Any format is acceptable and ABNF is not required.

**Comment by deoren** [comment]
Is this issue still valid, or should it be closed out?

**Comment by rgerhards** [comment]
The answer given in https://github.com/rsyslog/rsyslog-doc/issues/28#issuecomment-37798396 actually is the formal definition. It's not ABNF, but very, very close. Duplicating it in ABNF would probably end up in slight differences on further updates (as usual with duplicated content). So basically it may be worth mentioning the two lexer/grammar files within the doc.

Side-note: the full config language (all three formats) CANNOT be given in ABNF or anything else, as it is not even a context-free language. Thus we needed to make some "dirty tricks" within the lexer and grammar files. Just so everyone knows.
