### ISSUE TITLE
`exec_template()` is not documented in RainerScript functions chapter

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog-doc#342]
There is no `exec_template()` description in RainerScript functions chapter: http://www.rsyslog.com/doc/v8-stable/rainerscript/functions.html
The only reference I've found is here: http://www.rsyslog.com/how-to-use-set-variable-and-exec_template/

And by the way what is faster?
- join strings using `set $.newtag = $.var1 & "." & $.var2 & "." & $.var3;
- use `exec_template()` with template like "%$.var1%.%$.var2%.%$var3"

**Comment by davidelang** [comment]
On Thu, 8 Jun 2017, Yury Bushmelev wrote:

> There is no `exec_template()` description in RainerScript functions chapter: http://www.rsyslog.com/doc/v8-stable/rainerscript/functions.html
> The only reference I've found is here: http://www.rsyslog.com/how-to-use-set-variable-and-exec_template/

patches welcome :-)

thanks for pointing this out even if you can't update the docs

> And by the way what is faster?
> - join strings using `set $.newtag = $.var1 & "." & $.var2 & "." & $.var3;
> - use `exec_template()` with template like "%$.var1%.%$.var2%.%$var3"

I would expect the set to be faster

David Lang

**Comment by rgerhards** [comment]
```set``` is definitely faster.

**Comment by deoren** [comment]
> @jay7x: There is no exec_template() description in RainerScript functions chapter

Looks like it was added by @dud225 in 7f890e3eae0074c51a361fc395f7082b6d62b279.

Closing since this has been resolved. Please reopen or sound off in case I'm overlooking something.
