### ISSUE TITLE
Discard syntax

### ISSUE THREAD

**Issue by OlafvdSpek** [rsyslog/rsyslog-doc#347]
http://www.rsyslog.com/doc/v8-stable/configuration/actions.html says `~` is discard but AFAIK `~` is deprecated and `stop` should be used instead.

**Comment by davidelang** [comment]
both work, but the recommendation is to use 'stop' as it makes it easier for 
people who aren't as familiar with rsyslog to understand what's going on.

There is no schedule to stop supporting the legacy config, it's just frequently 
not as clear as the new style config.

It's good to update the docs, but they shouldn't make too much of the 
'depreciated' status.
