### ISSUE TITLE
imfile cant't discovry new files 

### ISSUE THREAD

**Issue by zhong9257** [rsyslog/rsyslog-doc#357]
use imfile. the path = /app/\*/\*/\*.log.
during rsyslog running, new log file generate in the directory "/app/\*/\*".and the rsyslog cant't konw this things,it not to gather the content of the new log file.
After restart rsyslog,imfile can gather the content of new log file.

Can imfile discover the new log file during rsyslog running

**Comment by davidelang** [comment]
IIRC, rsyslog only allows one layer of wildcards in the path.

**Comment by zhong9257** [comment]
Version 8.25.0 [v8-stable] 2017-02-21
- imfile: add support for wildcards in directory names
  This now permits to monitor newly created directories without altering
  the configuration.

  path = /app/*/*/*.log .   Just the log file exist before staring rsyslog,imfile works well.
my problem is  imfile can't discover the new log file during rsyslog running

**Comment by davidelang** [comment]
On Fri, 21 Jul 2017, zhong9257 wrote:

> Version 8.25.0 [v8-stable] 2017-02-21
> - imfile: add support for wildcards in directory names
>  This now permits to monitor newly created directories without altering
>  the configuration.
>
>  path = /app/*/*/*.log .   Just the log file exist before staring rsyslog,imfile works well.
> my problem is  imfile can't discover the new log file during rsyslog running

right, but I think it only sets up the inotify for new files with one wildcard 
int he path name

so /app/foo/*/*.log would work, but /app/*/*.log would not.

**Comment by zhong9257** [comment]
thank you!I have a try tomorrow.
