### ISSUE TITLE
Request: Tweak wording for a ruleset's associated queue object

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#383]
From `development/config_data_model.rst`:

> Note that a ruleset has an associated queue object. In most cases, it needs not to be configured as a real queue (not one in direct mode) as that is only required in special cases.

I'm getting hung up on the wording: Is this saying that a ruleset should use direct mode in most cases or a real queue?

**Comment by rgerhards** [comment]
It actually depends. queue should be used if:
* it is bound to an input
* it is used to run multiple actions independently, e.g. 2 places to forward to

For all other uses cases (if I am not overlooking something), a queue is not useful.

**Comment by deoren** [comment]
@rgerhards Thanks for your feedback. 

I just created PR #398 where I attempted to merge your additional information into the relevant section. I also linked to the other two related Queues docs so the reader can jump to there if needed.
