### ISSUE TITLE
rsyslog documentation doesn't explicitly state that configuration parameters are NOT case sensitive

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#391]
Unless I overlooked it somewhere, I didn't see it explicitly mentioned that the configuration parameters within the ryslog configuration file are not case sensitive.

I plan to review the documentation more thoroughly and submit a PR so that the docs clearly state that this is the case. If it's already stated elsewhere, I will replicate that statement to other portions of the documentation to help emphasize the fact.

http://www.rsyslog.com/doc/v8-stable/configuration/basic_structure.html

**EDIT**

Confirmation re case-insensitive nature of configuration parameters given here:

http://lists.adiscon.net/pipermail/rsyslog/2017-November/044971.html

**Comment by deoren** [comment]
@rgerhards Just in case I missed it, are legacy configuration statements case-sensitive?

**Comment by rgerhards** [comment]
no

**Comment by deoren** [comment]
@rgerhards  Thanks for confirming.

**Comment by deoren** [comment]
@rgerhards Are the phrases "legacy configuration statements" and "legacy configuration directives" interchangeable?

**Comment by rgerhards** [comment]
yes. Now that you said this, I think we should really try to use these terms (config format name) consistently. I think we should base it on this here: http://www.rsyslog.com/doc/master/configuration/conf_formats.html

Just be aware that I will probably slightly rename the "sysklogd" format as it may make sense to include some of the very basic enhancements done in rsyslog. That tripple has the advantage that it also is very easy to explain what is good to use(sysklogd/RainerScript) and what is really bad "legay"). Again, I'll probably propose some better names for the tripple.

**Comment by deoren** [comment]
> @rgerhards: Now that you said this, I think we should really try to use these terms (config format name) consistently. 

Thanks for the details.

Just to make sure I'm understand, are you saying that ...

- (1) we should use the same config format name for both legacy and RainerScript formats
- (2a) that we should consistently use the config format name of `legacy rsyslog` for the legacy format throughout the documentation
- (2b) we refer to the new config format name as RainerScript throughout the documentation

I assume that you mean the second option?

On a related note, I notice that there are different names for the parameters:

- http://www.rsyslog.com/doc/v8-stable/configuration/modules/omfile.html (`configuration parameters`)
- http://www.rsyslog.com/doc/v8-stable/configuration/modules/ompipe.html (`configuration directives`)

Is that desired?

> @rgerhards: That tripple has the advantage that it also is very easy to explain what is good to use(sysklogd/RainerScript) and what is really bad "legay"). Again, I'll probably propose some better names for the tripple.

I too like how the formats are separated out into their own section versus nesting them like they're currently grouped in the v8-stable docs right now:

http://www.rsyslog.com/doc/v8-stable/configuration/basic_structure.html#configuration-file

**Comment by rgerhards** [comment]
> Just to make sure I'm understand, are you saying that ...
> 
> (1) we should use the same config format name for both legacy and RainerScript formats
> (2a) that we should consistently use the config format name of legacy rsyslog for the legacy format throughout the documentation
> (2b) we refer to the new config format name as RainerScript throughout the documentation
> I assume that you mean the second option?

more or less... I mean we actually have three different configuration formats. We should call each of the three ones by the same name, no matter where we use it.

I am still rethinking on the renaming. I wonder if that triple would make sense

* **enhanced syslogd format** - in my recent update called "sysklogd format". 
  I use "enhanced" because I think it would be useful to contain constructs like
  ```msg: contains: "test" /var/log/some.log```
  I mean all those easy and clean things that you can do on a single line without getting into any confusion. This exactly is the set of "legacy" format that is still good to use, because it doesn't cause confusion. It's also the part that is used by most distros.
* **rsyslogd format** - so far called "RainerScript". 
  Sounds more natural, the trademark issue is probably gone away. Downside: may confuse people as "RainerScript" by now is well known. So it's a bit hard of a decision...
* **obsolete legacy format** - so far called "legacy rsyslog"
  The intent is to convey even by the name alone that you really, really never should use this. Another good name would be "drive me crazy format" ... ok, just kidding ;-)

What do you think? @davidelang @radu-gheorghe @mbiebl @Whissi any thoughts?
> 
> On a related note, I notice that there are different names for the parameters:
> 
> http://www.rsyslog.com/doc/v8-stable/configuration/modules/omfile.html (configuration parameters)
> http://www.rsyslog.com/doc/v8-stable/configuration/modules/ompipe.html (configuration directives)
> Is that desired?

No! It was just never consistently set up... I think ```parameter``` is probably the best term.

**Comment by deoren** [comment]
> @rgerhards: rsyslogd format - so far called "RainerScript".

To my mind, if taken literally, it implies that it is the preferred/native format that users should use when configuring rsyslog. I would almost expect to see that term used to contrast against a format for another daemon, or I suppose the "enhanced" format.

Although it may seem redundant at first glance, I think that using both "obsolete" and "legacy" to describe the older format lends extra weight behind the implied suggestion to not use it.

> @rgerhards: Downside: may confuse people as "RainerScript" by now is well known. So it's a bit hard of a decision...

I agree that it is a hard decision, but if you make it clear that `RainerScript` is the deprecated name for the current format in the "triple" list then you should be able to get away with using the new `rsyslogd format` term through the rest of the document. Maybe something like this:

> - `enhanced syslogd format` - previously known as the "sysklogd" format, this configuration format is widely known, actively supported and occasionally enhanced with new features. This format is recommended for simple use cases where the entire statement cleanly fits on a single line.
> 
> - `rsyslogd format` - previously known as "RainerScript", this is the current, best and most precise format to use for non-trivial use cases where more than one line is needed. This format is available in rsyslog v6 and above.
> 
> - `obsolete legacy format` - previously known as the "legacy" or "legacy rsyslog" format, this format is intended only for backwards compatibility purposes. By providing this support, existing configurations continue to work when upgrading to a newer version of rsyslog. This format is notoriously difficult to use, should _not_ be used for new configurations and is not supported by many of the newer modules available in rsyslog v6 and above. Anyone using this format is recommended to migrate to the `rsyslogd` or `enhanced syslogd` formats.

Later in the docs if there is a part that focuses heavily on formats we could mention the deprecated "RainerScript" term again with a note that it is now known as `rsyslogd format`.

> @rgerhards: It was just never consistently set up... I think parameter is probably the best term.

That makes sense. I'll try to work that in the next batch of changes I'm working on. I hope to submit a PR for this work in the next day or so to get your feedback.

**Comment by rgerhards** [comment]
I also had another round of thinking: how about basic, advanced, obsolete
format or simple, sophisticated and obsolete?

That would also flow very naturally in the text.

Rainer

Sent from phone, thus brief.

**Comment by deoren** [comment]
> @rgerhards: I also had another round of thinking: how about basic, advanced, obsolete 

That could work, but I wonder whether the generic nature of the format names would make discovery more difficult. I am partial to the last proposal myself.

That said, the purpose of each format is made clear by the name.

I haven't looked into it yet, but if Sphinx/reStructured text supports variables of some sort we could start updating the docs to use the variables or constants in place of the old names. We could then easily test swapping out the values for the variables/constants to see how well the content reads and what kind of results we get with searching the content (e.g., searching the epub on an ebook reader as I often do now).

**Comment by deoren** [comment]
Follow-up to my last remark:

Sphinx apparently _does_ support substitutions:

- http://www.sphinx-doc.org/en/stable/rest.html#substitutions
- http://www.sphinx-doc.org/en/stable/config.html#confval-rst_prolog
- http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-definitions
- http://docutils.sourceforge.net/docs/ref/rst/directives.html#replace

I'll try to experiment with this soon to see how well it works. If it's easy enough, we may want to build a common include file to cover phrases that we use a lot throughout the document. This would make it easier to keep terms consistent and would make swapping them out later easier.

**Comment by davidelang** [comment]
On Sat, 9 Dec 2017, Rainer Gerhards wrote:

>> Just to make sure I'm understand, are you saying that ...
>>
>> (1) we should use the same config format name for both legacy and RainerScript formats
>> (2a) that we should consistently use the config format name of legacy rsyslog for the legacy format throughout the documentation
>> (2b) we refer to the new config format name as RainerScript throughout the documentation
>> I assume that you mean the second option?
>
> more or less... I mean we actually have three different configuration formats. We should call each of the three ones by the same name, no matter where we use it.
>
> I am still rethinking on the renaming. I wonder if that triple would make sense
>
> * **enhanced syslogd format** - in my recent update called "sysklogd format".
>  I use "enhanced" because I think it would be useful to contain constructs like
>  ```msg: contains: "test" /var/log/some.log```
>  I mean all those easy and clean things that you can do on a single line without getting into any confusion. This exactly is the set of "legacy" format that is still good to use, because it doesn't cause confusion. It's also the part that is used by most distros.

> * **rsyslogd format** - so far called "RainerScript".
>  Sounds more natural, the trademark issue is probably gone away. Downside: may confuse people as "RainerScript" by now is well known. So it's a bit hard of a decision...

I don'tthink there is a problem with this, there can be a note explaining the 
details and pointing out  that this format was introduced in v6

> * **obsolete legacy format** - so far called "legacy rsyslog"
>  The intent is to convey even by the name alone that you really, really never should use this. Another good name would be "drive me crazy format" ... ok, just kidding ;-)

Yes!! we need to diffentiate between the old things that are still good to use, 
and the old things that aren't. I see too many people working to eliminate the 
'enhanced syslog format' lines, it's mostly wasted effort.
k

**Comment by davidelang** [comment]
On Sat, 9 Dec 2017, Deoren Moor wrote:

>> - `obsolete legacy format` - previously known as the "legacy" or "legacy 
>> rsyslog" format, this format is intended only for backwards compatibility 
>> purposes. By providing this support, existing configurations continue to work 
>> when upgrading to a newer version of rsyslog. This format is notoriously 
>> difficult to use, should _not_ be used for new configurations and is not 
>> supported by many of the newer modules available in rsyslog v6 and above. 
>> Anyone using this format is recommended to migrate to the `rsyslogd` or 
>> `enhanced syslogd` formats.

it's not that the 'obsolete leagacy format' isn't supported in newer modules, 
but rather than new features are not available in this format. Old features 
continue to be supported in newer versions of the modules.

**Comment by davidelang** [comment]
> I also had another round of thinking: how about basic, advanced, obsolete
> format or simple, sophisticated and obsolete?

I like basic, advanced, obsolete. It does a good job of describing the 
differences and when to shift from basic to advanced. Sophisticated is not only 
much more typing, it is normally not a term used for config formats.

In the filters section where we are talking about the basic options (including 
the ":msg contains" type) we should note that in older versions there were 
performance advantages to avoid the advanced versions, but as of v8 there is no 
difference.

**Comment by deoren** [comment]
Update re Sphinx substitutions:

While it does appear to work, one shortcoming appears to be that you can't easily embed substitution references directly within formatted text. While you could emulate having the term use the same formatting by defining a separate substitution for each difference style of formatting, this would quickly end up becoming a maintenance pain. Instead, if we're fine with consistently using code styling for the terms (or any specific formatting intended for use with terms) and omitting those terms from the surrounding formatting then I think the substitution approach will work out.

For example, here is a line as it was before using substitutions where the term is in bold with the surrounding text:

```
**It is recommended to use RainerScript format.**
```

and after using a substitution:

```
**It is recommended to use** |FormatsAdvancedNewName| **format.**
```

With the substitution defined like so within an include file:

```
.. |FormatsAdvancedOldName| replace:: ``RainerScript``
```

we end up with the first part bold, then code styling for the term and then bold again for the latter  portion of the sentence. After reviewing freshly generated epub and html output, it appears that the results still work well enough to make the conversion to using substitutions worth it in the end.

**Comment by deoren** [comment]
> @davidelang: In the filters section where we are talking about the basic options (including
the ":msg contains" type) we should note that in older versions there were
performance advantages to avoid the advanced versions, but as of v8 there is no
difference.

Spun off #413 to handle that.

**Comment by deoren** [comment]
> @davidelang: I like basic, advanced, obsolete. It does a good job of describing the differences and when to shift from basic to advanced. Sophisticated is not only much more typing, it is normally not a term used for config formats.

Visually, I have to agree. Having single word descriptions of the formats makes it less of a chore to read over. I suppose over time the other format names will fade, so having shorter names might not be so bad.

I suppose if we take the terms at face value however, perhaps "obsolete" should be "deprecated" instead since that format is still supported?

**Comment by deoren** [comment]
@rgerhards @davidelang 

In a8eb05414e3da9f92efc0066a398c2c18556410f I tested two changes.

## Substitution of terms

It's a little muddled, but a8eb05414e3da9f92efc0066a398c2c18556410f is an illustration of what I am thinking of in regards to using substitution for terms. It turns out that Sphinx has a [`rst_prolog` configuration option](http://www.sphinx-doc.org/en/stable/config.html#confval-rst_prolog) to include a "string" at the top of every source file read. That allows us to place all substitutions in one place and then reference them within the source files without having to use include calls at the top of each of those files that contains a substitution reference.

The current values in the `rst_prolog` option are mostly for illustration, though I do like keeping the "legacy" word around for the old format since it's been used so much. Prepending "obsolete" in front of it still allows for heavily discouraging its use.

## Dynamic release version with date/commit info

Re 'muddled', I was playing with having the release version dynamically generated to include date of output generation along with the associated commit.

Prior to this change I was using a small shell script to generate that dynamic value before:

```
version=$(grep -E '^version' source/conf.py | awk '{print $NF}' | sed "s/'//g")
datestamp=$(date '+%Y%m%d')
commit=$(git describe | awk -F'-' '{print $NF}')
release="${version}.${datestamp}.${commit}"

declare -a formats
formats=(
  epub
  html
)

for format in "${formats[@]}"
do
    sphinx-build -D version="$version" -D release="$release" -b $format source build
done
```

It's not pretty, but it worked.

Unless having the date and commit info as a permanent part of the doc release/version string is popular, I suspect that going back to the shell script approach to generate that value dynamically is the way to go.

**Comment by deoren** [comment]
Just in case it is useful, I went ahead and uploaded the generated HTML content for review:

- http://temp.whyaskwhy.org/rsyslog/i-391-conf-formats/
- http://temp.whyaskwhy.org/rsyslog/i-391-param-case/

**Comment by davidelang** [comment]
On Sun, 10 Dec 2017, Deoren Moor wrote:

> I suppose if we take the terms at face value however, perhaps "obsolete" should be "deprecated" instead since that format is still supported?

I don't like "deprecated"

For one thing, that's already been used for things with a different meaning.

For another, I don't think it's strong enough discouragement for people

We could add a fourth catagory, "broken" or "unsupported" for the very few 
things that do not work any more (BSD filters for example)

But we want to make it VERY clear to people that they should not write new stuff 
with the many lines of $someconfig followed by the stuff affected by those 
lines.

**Comment by deoren** [comment]
> @davidelang : I don't like "deprecated"
> 
> For one thing, that's already been used for things with a different meaning.
> 
> For another, I don't think it's strong enough discouragement for people
> 
> We could add a fourth catagory, "broken" or "unsupported" for the very few
> things that do not work any more (BSD filters for example)
> 
> But we want to make it VERY clear to people that they should not write new stuff
> with the many lines of $someconfig followed by the stuff affected by those
> lines.

I don't like "deprecated" either, but it seems to be the closest match to the current situation: the format is still supported, but kept around primarily for backwards compatibility reasons, and discouraged from use in new configurations.

Perhaps bending the definition of "obsolete" a little to help get the point across is the better ideal to uphold vs the accuracy of the terminology. ;)

**Comment by davidelang** [comment]
On Sun, 10 Dec 2017, Deoren Moor wrote:

> I don't like "deprecated" either, but it seems to be the closest match to the current situation: the format is still supported, but kept around primarily for backwards compatibility reasons, and discouraged from use in new configurations.
>
> Perhaps bending the definition of "obsolete" a little to help get the point across is the better ideal to uphold vs the accuracy of the terminology. ;)

Unfortunantly, we've been referring to the basic config statements as 
depriciated for years, so that term is polluted.

**Comment by rgerhards** [comment]
yeah, I would follow @davidelang's reasoning in favor of "obsolete".

Being not a native speaker, I asked google[1] what the definition of "obsolete" actually is. First match was:
"no longer produced or used; out of date.
"the disposal of old and obsolete machinery"
synonyms:	out of date, outdated, outmoded, old-fashioned;"

This sounds like a pretty good description of the situation. Nevertheless, I am not a native speaker, so I may miss some fine parts of language use here.

[1] https://www.google.de/search?q=define%3Aobsolete&oq=define%3Aobsolete

**Comment by deoren** [comment]
> @rgerhards: no longer produced or used; out of date.

I think the second part definitely fits, but it is certainly still used. To be clear though, I like the heavy emphasis on "do not use this, there are better ways" that is conveyed by the word. I just had a second thought that "deprecated" would a better fit (regardless of it not being my first choice), provided that the project had an EOL target (date or specific version) in mind for the legacy format.

**Comment by davidelang** [comment]
On Sun, 10 Dec 2017, Deoren Moor wrote:

> I just had a second thought that "deprecated" would a better fit (regardless 
> of it not being my first choice), provided that the project had an EOL target 
> (date or specific version) in mind for the legacy format.

we don't ever plan to eliminate the legacy format for backwards compatibility 
reasons (there's no big advantage to do so, and  all sorts of reasons not to)

**Comment by deoren** [comment]
Since the original focus of this issue was to make clear that configuration parameters are case-insensitive, I move that we close this ticket out. The tangent topics (which I'm guilty of starting) have been worked on and could be refined on more specific/focused issues that just relate back to this one.

Ex: v1 files, official config format terms, substitutions, ...

**Comment by deoren** [comment]
> @davidelang: we don't ever plan to eliminate the legacy format for backwards compatibility
reasons (there's no big advantage to do so, and  all sorts of reasons not to)

Gotcha. Maybe a point for discussion later down the road once all LTS versions of current distros have moved forward a bit.

**Comment by davidelang** [comment]
On Mon, 11 Dec 2017, Deoren Moor wrote:

>> @davidelang: we don't ever plan to eliminate the legacy format for backwards compatibility
> reasons (there's no big advantage to do so, and  all sorts of reasons not to)
>
> Gotcha. Maybe a point for discussion later down the road once all LTS versions of current distros have moved forward a bit.

The thing is that even if every distro were to upgrade to the latest rsyslog, 
admins of those machines want to just be able to upgrade and not have to go back 
and change configs that were created years ago.

So we should never make a change that breaks an existing, working config (if we 
can at all avoid it), and this means that the obsolete config options are going 
to remain pretty much forever.
