### ISSUE TITLE
imuxsock module documentation: What exactly do the 'SysSock.Name' and 'SysSock.Use' parameters do?

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#397]
- Is the `SysSock.Name` parameter used to specify the replacement for `/dev/log` or is that parameter used to specify another socket that is _in addition to_ `/dev/log` as an input source?

- Does `SysSock.Use="on"` tell rsyslog to read from `/dev/log` or just from whatever is the default? If `SysSock.Name` is specified, does `SysSock.Use="on"` now refer to using the socket specified by `SysSock.Name`?

Refs: http://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html

**Comment by deoren** [comment]
Based on some testing, it appears that this configuration tells rsyslog to skip reading from `/dev/log` and read from `/run/systemd/journal/syslog` instead:

```
module(

    load="imuxsock"
 
    # Do not attempt to read /dev/log; systemd is controlling and supervising access to this socket
    sysSock.Use="off"

    # Here we replace what the stock /etc/rsyslog.d/list.conf fragment provides
    # by explicitly specifying the input socket name/path
    sysSock.Name="/run/systemd/journal/syslog"
)
```

**Comment by deoren** [comment]
After much research (more to do), I believe I understand the relationship between the `/dev/log` socket, systemd and imuxsock a bit better, but I still have a few sticking points.

## Ubuntu

- `/dev/log` symlinked to `/run/systemd/journal/dev-log` (**write-target**)
-  imuxsock by default will read from `/run/systemd/journal/syslog` (**read-source**) as if you had specified 

## CentOS 7
- `/dev/log` a real socket, _owned_ by systemd, no symlink in place
- for RHEL-based systems, it appears you have to explicitly specify the `sysSock.Name` parameter as `sysSock.Name="/run/systemd/journal/syslog"` to receive the data that systemd passes over

**Comment by deoren** [comment]
Actually, after some additional testing it appears that this will work fine for CentOS 7 systems:

```
module(load="imuxsock" sysSock.Use="off)
```

Is `sysSock.Use` used to control whether rsyslog attempts exclusive access to `/dev/log` (which conflicts with systemd owning that socket)?

**Comment by deoren** [comment]
@rgerhards any pointers on this? After much testing I feel like I'm just going in circles. I've observed some behavior that sort of makes sense, but I'm not 100% sure I understand what is intended by the `SysSock.Use` and `SysSock.Name` parameters.

## Version of rsyslog

`[root@localhost redhat]# rpm -q rsyslog`
```
rsyslog-8.30.0-4.el7.x86_64
```

## Test `/etc/rsyslog.conf` configuration

`grep -Ev '^$|^\s*#' /etc/rsyslog.conf`

```
module(
    load="imuxsock"
    SysSock.Use="on"
    SysSock.Name="/run/systemd/journal/syslog"
)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
module(load="immark")  # provides --MARK-- message capability
module(load="builtin:omfile" Template="RSYSLOG_FileFormat")
global (
    action.reportSuspension="on"
    action.reportSuspensionContinuation="on"
    workDirectory="/var/lib/rsyslog"
    processInternalMessages="off"
)
$WorkDirectory /var/lib/rsyslog
$RepeatedMsgReduction off
$IncludeConfig /etc/rsyslog.d/*.conf
*.info;mail.none;authpriv.none;cron.none                /var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  /var/log/maillog
cron.*                                                  /var/log/cron
*.emerg                                                 :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log
```

- `systemctl status rsyslog` output: systemd and rsyslog emitted status info present (start, stop, etc)
- `/var/log/messages` file: updated contents from boot and when restarting daemons (e.g., rsyslog, such as chronyd)

## `module(load="imuxsock" SysSock.Name="/run/systemd/journal/syslog")`

Same as with "base" config:

- `systemctl status rsyslog` output: systemd and rsyslog emitted status info present (start, stop, etc)
- `/var/log/messages` file: updated contents from boot and when restarting daemons (e.g., rsyslog, such as chronyd)

Presumably this is because `SysSock.Use` defaults to **on** if not explicitly configured.

## `module(load="imuxsock" SysSock.Use="on")`

- `systemctl status rsyslog` output: systemd "Starting" and "Started" output only for rsyslog
- `/var/log/messages` file: updated contents from boot and when restarting daemons (e.g., rsyslog, such as chronyd)

## `module(load="imuxsock" SysSock.Use="off")`

- `systemctl status rsyslog` output: systemd and rsyslog emitted status info present (start, stop, etc)
- `/var/log/messages` file: updated with boot messages only (not even rsyslog stop/start messages are logged)

**Comment by rgerhards** [comment]
I am sure .use tells wether to listen on the socket or not.

.name should be the socket name (path, e.g /dev/log) to use. Systemd
mangles with the socket in the background, so it may confuse things.

Does that help?

Rainer

Sent from phone, thus brief.

Am 01.12.2017 20:46 schrieb "Deoren Moor" <notifications@github.com>:

**Comment by deoren** [comment]
> @rgerhards: I am sure .use tells wether to listen on the socket or not.
> 
> .name should be the socket name (path, e.g /dev/log) to use. Systemd mangles with the socket in the background, so it may confuse things.

Thanks for the feedback. Is the intention for SysSock.name to offer an override for the default log socket and sysSock.use for toggling on/off listening on either the custom socket name or the default?

Speaking of the default, is that determined by the type of system rsyslog runs on or does it always default to attempting to read the `/dev/log` socket? 

For example:

- Ubuntu 14.04 doesn't have journald, so presumably rsyslog would try to use `/dev/log`. 
- Ubuntu 16.04 does use journald, so does rsyslog skip trying for `/dev/log` and try for `/run/systemd/journal/syslog` instead?

**Comment by rgerhards** [comment]
Sent from phone, thus brief.

Am 01.12.2017 21:18 schrieb "Deoren Moor" <notifications@github.com>:

@rgerhards <https://github.com/rgerhards>: I am sure .use tells wether to
listen on the socket or not.

.name should be the socket name (path, e.g /dev/log) to use. Systemd
mangles with the socket in the background, so it may confuse things.

Thanks for the feedback. Is the intention for SysSock.name to offer an
override for the default log socket and sysSock.use for toggling on/off
listening on either the custom socket name or the default?


Yes

Speaking of the default, is that determined by the type of system rsyslog
runs on or does it always default to attempting to read the /dev/log socket?


It always defaults to that but..

For example:

   - Ubuntu 14.04 doesn't have journald, so presumably rsyslog would try to
   use /dev/log.
   - Ubuntu 16.04 does use journald, so does rsyslog skip trying for
   /dev/log and try for /run/systemd/journal/syslog instead?


Under systemd (99 percent sure), we get an open file descriptor passed in.
So we do not know the socket name. That said, the config parameters do
possibly not work under systemd...

Rainer



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rsyslog/rsyslog-doc/issues/397#issuecomment-348603980>,
or mute the thread

**Comment by rgerhards** [comment]
Oh, and it has nothing to do with the journald. It just depends on systemd.

Rainer

Sent from phone, thus brief.

Am 01.12.2017 21:18 schrieb "Deoren Moor" <notifications@github.com>:

**Comment by deoren** [comment]
@rgerhards Thanks for the feedback.

I think I follow: 

- rsyslog always tries for `/dev/log` by default, provided that you don't set `sysSock.Use="off"` or override it

- If you set `sysSock.Use="off"` and then specify an alternate socket via `sysSock.Name` then rsyslog does not appear to ingest messages from any valid socket (`/dev/log` or `/run/systemd/journal/syslog`). If you specify `global(processInternalMessages="off")` then systemd receives rsyslog's emissions (start, stop, HUP, etc).

Questions:

- If you specify `sysSock.Name="/run/systemd/journal/syslog"` , does rsyslog skip trying for `/dev/log`?

**Comment by rgerhards** [comment]
Sent from phone, thus brief.

Am 01.12.2017 21:34 schrieb "Deoren Moor" <notifications@github.com>:

@rgerhards <https://github.com/rgerhards> Thanks for the feedback.

I think I follow:

   -

   rsyslog always tries for /dev/log by default, provided that you don't
   set sysSock.Use="off" or override it
   -

   If you set sysSock.Use="off" and then specify an alternate socket via
   sysSock.Name then rsyslog does not appear to ingest messages from any
   valid socket (/dev/log or /run/systemd/journal/syslog). If you specify
   global(processInternalMessages="off") then systemd receives rsyslog's
   emissions (start, stop, HUP, etc).

Questions:

   - If you specify sysSock.Name="/run/systemd/journal/syslog" , does
   rsyslog skip trying for /dev/log?


It's actually quite simple. It is whatever is specified in .name with a
default of /dev/log - instead on systemd systems, where the systemd config
takes precedence (I think you can even specify multiple sockets with
systemd, but I don't know). Again, 99% sure...

Rainer



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rsyslog/rsyslog-doc/issues/397#issuecomment-348607591>,
or mute the thread

**Comment by deoren** [comment]
> @rgerhards: It's actually quite simple. It is whatever is specified in .name with a
default of /dev/log - instead on systemd systems, where the systemd config
takes precedence (I think you can even specify multiple sockets with
systemd, but I don't know). Again, 99% sure...

Thanks. Sorry to be a pest about this.

Maybe I'm seeing a bug and that is what has me confused.

If I have either of these configurations (fragments below):

```
module(load="imuxsock" SysSock.Use="on")
global(processInternalMessages="off")
```

```
module(load="imuxsock")
global(processInternalMessages="off")
```

With that setup, I find that rsyslog attempts to read from `/dev/log` on a systemd system (v8.30.0 and v8.31.0), and apparently succeeds, but none of the detailed start/stop/HUP messages are shown in `systemctl status rsyslog`.

But if I use this configuration, then the output _is_ shown in `systemctl status rsyslog` as well as `/var/log/messages`:

```
module(load="imuxsock" sysSock.name="/run/systemd/journal/syslog")
global(processInternalMessages="off")
```

It appears that I have to explicitly use `sysSock.name="/run/systemd/journal/syslog"` if I want the output to show in `systemctl status rsyslog`. Is that normal?

**Comment by rgerhards** [comment]
That sounds strange. Which platform? Packages from our repo? How is systemd
configured (sorry, I don't know where this can be looked up)?

Rainer

Sent from phone, thus brief.

Am 01.12.2017 22:12 schrieb "Deoren Moor" <notifications@github.com>:

**Comment by deoren** [comment]
My test environment:

- CentOS Linux release 7.4.1708 (Core), with all of the latest patches
- VMware Workstation 12.5.8 hypervisor
- Using Adiscon yum repo: http://rpms.adiscon.com/v8-stable/rsyslog.repo
- first tested `rsyslog-8.30.0-4.el7.x86_64`
- then tried `rsyslog-8.31.0-3.el7.x86_64` 

So with the following configuration, should imuxsock "just work" and show the expected output in `systemctl status rsyslog` and also within `/var/log/messages`?

```
module(load="imuxsock")
global(processInternalMessages="off")
```

**Comment by deoren** [comment]
I should also say that I commented out the stock `/etc/rsyslog.d/listen.con` file that contains this entry:

```
$SystemLogSocketName /run/systemd/journal/syslog
```

I did so far seeing that this message was logged by rsyslog (as covered by rsyslog/rsyslog#1367):

```
rsyslogd: command 'SystemLogSocketName' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.31.0 try http://www.rsyslog.com/e/2222 ]
```

`[root@localhost redhat]# rpm -qf /etc/rsyslog.d/listen.conf`
```
systemd-219-42.el7_4.4.x86_64
```

The `/etc/rsyslog.d/listen.conf` file is evidently provided by the systemd package.

**Comment by rgerhards** [comment]
I do not know how rhel/CentOS has configured systemd and journal. It
depends on this as well. I think they by default do not use imuxsock but
imjournal. @davidelang do you happen to know?

Sent from phone, thus brief.

Am 01.12.2017 22:28 schrieb "Deoren Moor" <notifications@github.com>:

**Comment by deoren** [comment]
> @rgerhards: How is systemd configured (sorry, I don't know where this can be looked up)?
> 
> do not know how rhel/CentOS has configured systemd and journal. It depends on this as well. I think they by default do not use imuxsock but imjournal. @davidelang do you happen to know?

The default setting of `ForwardToSyslog=yes` is noted within `/etc/systemd/journald.conf` if that is what you're asking.

**Comment by rgerhards** [comment]
Imho this looks like a big mess. I would not outrule that our packages are
not fully compatible - especially after what I have seen the past days :-(

Maybe worth opening an issue in rsyslog itself. I admit, though, that I
will probably not be able to solve it quickly and the more help the
better... Packaging is definitely not my core competency...

But maybe it's something that just needs to go to the doc. We need to find
out in why case...

Sent from phone, thus brief.

Am 01.12.2017 22:31 schrieb "Deoren Moor" <notifications@github.com>:

**Comment by deoren** [comment]
@rgerhards Sorry, I really thought this was just a case of my not comprehending the docs and was looking for some verbose details to help craft an enhancement PR.

I'll submit as a new issue and reference this one.

**Comment by rgerhards** [comment]
It's good that it came to light...

Sent from phone, thus brief.

Am 01.12.2017 22:53 schrieb "Deoren Moor" <notifications@github.com>:

**Comment by deoren** [comment]
@rgerhards Working on a new ticket now. Is the following the expected behavior from your point of view? 

1. Load the module without any special options (e.g., `module(load="imuxsock")`)
1. imuxsock works out where the applicable input socket is located on its own, uses that to read in messages from system
1. Route emitted messages from rsyslog back systemd when using `processInternalMessages="off"` (apparent default with v8.21.0 and newer)

**Comment by deoren** [comment]
Typo-fixed version of last comment (for easier reading by email):

> @rgerhards Working on a new ticket now. Is the following the expected behavior from your point of view? 
> 
> 1. Load the imuxsock module without any special options (e.g., `module(load="imuxsock")`)
> 1. imuxsock module works out where the applicable input socket is located on its own, uses that to read in messages [passed from systemd](https://www.freedesktop.org/software/systemd/man/journald.conf.html) (happens to be `/run/systemd/journal/syslog`)
> 1. Route emitted messages from rsyslog back to systemd when using `processInternalMessages="off"` (apparently the default with v8.21.0 and newer)

**Comment by deoren** [comment]
As posted to https://github.com/rsyslog/rsyslog/issues/2150#issuecomment-350058802:

> @deoren: From what I understand of our recent conversations, the expected behavior for a systemd system is that if imuxsock's SysSock.Use and SysSock.Name parameters are left at their default values (by using a standard module load statement: module(load="imuxsock")), then /dev/log should be ignored and rsyslog will instead use the value passed to it by systemd (e.g., /run/systemd/journal/syslog). If systemd is not in-use, then rsyslog (with default imuxsock parameter values) will manage /dev/log directly.

I plan to work on a draft version of the imuxsock documentation in the next few days to make sure I understand how imuxsock works and hopefully spell it out for future readers of that doc. 

I suspect my problem is that I lack knowledge of the inner workings of systemd, how standard UNIX sockets work (e.g., is it standard behavior to unlink a socket when a daemon manages it?), but hopefully we can merge in some additional clarification to the imuxsock doc without weighing it down too much for those who already possess that knowledge.

**Comment by deoren** [comment]
@rgerhards What is the intended behavior when you set `sysSock.Use="off"` on a system where systemd is present/running? 

Earlier testing on a distro using systemd seems to indicate that this results in rsyslog listening to the systemd-provided `/run/systemd/journal/syslog` socket, but not attempting to takeover management of `/dev/log`.

I assume that the intended behavior when explicitly setting `SysSock.Use="on"` would be the exact same as not specifying any value at all since the default value is already "on".

As I look further into this, I don't see a way to tell rsyslog to _not_ listen on the socket provided by systemd. I'm still going over the `imuxsock.c` source code (and I've only ever dabbled in learning it), but from what I've been able to understand thus far, if rsyslog was built with systemd support it will automatically attempt to listen to the hard-coded socket once a valid path to the socket (and that it is a socket) is confirmed:

https://github.com/rsyslog/rsyslog/blob/cd4f27baf9bb412f9ee5f1d0287851afe5ddf316/plugins/imuxsock/imuxsock.c#L1140

Would it be useful to grow a parameter to supporting enabling/disabling of rsyslog listening on the `/run/systemd/journal/syslog` path via an imuxsock parameter? I don't have the necessary skills to add such a feature myself, but I could go ahead and create a ticket for later work.

With such an option, rsyslog could be told to not listen to the local `/dev/log` socket and not to listen to `/run/systemd/journal/syslog` either. At that point the particular instance running with this configuration would only listen to any custom locations setup with imuxsock input() definitions.

**Comment by davidelang** [comment]
if rsyslog is running imjournald it's not using /run/systemd/journal/syslog, 
it's making calls using  the systemd library to fetch new  logs via an api

syssock.name=/run/systemd/journal/syslog would give you the behavior you are 
talking about

**Comment by rgerhards** [comment]
systemd integration messes up with the original imuxsock code. Let me review and push a PR for that...

**Comment by deoren** [comment]
> @davidelang: If rsyslog is running imjournald it's not using /run/systemd/journal/syslog,
it's making calls using  the systemd library to fetch new  logs via an api

In this scenario, imjournal is not being used, just imuxsock.

> syssock.name=/run/systemd/journal/syslog would give you the behavior you are
talking about

I was wondering about that (and I believe I tested that scenario), but if I configure rsyslog that way, wouldn't that be configuring imuxsock to "own" the /run/systemd/journal/syslog socket, causing it to be unlinked and recreated?

> @rgerhards: systemd integration messes up with the original imuxsock code. Let me review and push a PR for that...

will take a look at that now.

**Comment by deoren** [comment]
Closing per #427.
