### ISSUE TITLE
html textboxes have not properly been converted and need fixing

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-doc#4]
The html doc uses textboxes for config file samples. These boxes have been converted as plain text, and so the config sample are unreadable. For an example, check the imuxsock doc, but that's unfortunately a problem all over the place.

**Comment by deoren** [comment]
@rgerhards I'm going to go out on a limb and say that this has been mostly resolved by now?

**Comment by rgerhards** [comment]
Full ACK on the ```mostly```. I wouldn't bet there are still some small spots, but we can fix them (if any) while we walk by. IIRC we still seem to have an issue with the site's stylesheet (some of the bullet lists render badly), but that's probably for next year. I guess we also need @alorbach to fix that (he manages the web site).

**Comment by deoren** [comment]
> @rgerhards: IIRC we still seem to have an issue with the site's stylesheet (some of the bullet lists render badly

Particular pages or just in general?

**Comment by rgerhards** [comment]
I added #459 after closing this. I think that's the only issue I see.
