### ISSUE TITLE
imuxsock module: Does the warning re CreatePath/Socket parameter placement apply to new style conf?

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#403]
From the current format:

> Note that it is vital not to place any other socket between the CreatePath and the Socket.

This appears to match the same statement in the legacy format portion of the doc. I assume that this comment does not apply here, or are multiple sockets allowed per imuxsock input?

In other words, I assume this is not valid?

`input(type="imuxsock" Socket="/path/to/socket1" CreatePath="on" Socket="/path/to/socket2")`

**Comment by rgerhards** [comment]
> This appears to match the same statement in the legacy format portion of the doc.

Right! Any order dependency (if you find more) refers to old-style. New style was specifically designed to do not depend on order.

**Comment by deoren** [comment]
@rgerhards Thanks for confirming, I've submitted a PR for that one item. 

I'll review the doc in more detail for other cases. On a related note, I plan to revisit rsyslog/rsyslog-doc#397 once I have a chance to finish going over my notes and collect my thoughts into something a little more coherent.

**Comment by rgerhards** [comment]
merged ;-)

BTW: if you include
```
closes https://github.com/rsyslog/rsyslog-doc/issues/403
```
Matching issues will automatically be closed upon merge of the PR. It's pretty handy.

Thanks for all the hard work on the doc! I hope to be able to at least have a first shot at the overall structure. I really think this needs work ;-)

**Comment by deoren** [comment]
> @rgerhards: BTW: if you include
> 
> `closes https://github.com/rsyslog/rsyslog-doc/issues/403`
> 
> at the bottom of the commit message, matching (mentioned) issues will automatically be closed upon merge of the PR. It's pretty handy.

Good tip, I didn't think of that. I know there is the "fixes" shorthand (and realized it would probably be too confident of a statement to make without review), but didn't realize that the `closes` statement would work here. I imagine that would make it a lot easier for you to manage closing out related issues. I'll try to remember to do that going forward.

> Thanks for all the hard work on the doc! 

Welcome. I hope to spend some more time with it in the next week depending on how time commitments work out on my end.

> I hope to be able to at least have a first shot at the overall structure. I really think this needs work ;-)

I look forward to it.
