### ISSUE TITLE
Update readme file to reflect current branch, download URL

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#405]
Proposed fixes/updates:

- Updates reference to stable branch: `v8-stable` instead of `v5-stable`
- Update download URL for Git for Windows (https://git-scm.com/download/win)
- Abstract the version of Python (Sphinx supports both Python 2.7.x and 3.x)

Potential Enhancements::

- Add step to generate epub file
- Use a virtualenv for installing `sphinx` package

**Comment by deoren** [comment]
@rgerhards Do you still feel this content is needed?

```
## Importing missing content
While this hasn't happened for some time now, there might be cases 
where a page from previous html-only doc seems to
be missing in rsyslog-doc. To recover it, check out the respective version (v8.1.6
is the latest v8 with html doc) and use this too to convert to rst:

$ pandoc -f html -t rst <html_file> -o <output_file>

Nowadays, it would be rather unexpected that this might really be needed, but
we still wanted to include the information.
```

**Comment by rgerhards** [comment]
I think we can remove that ;-)

**Comment by rgerhards** [comment]
@deoren this can **not** yet be closed, right?

**Comment by deoren** [comment]
I was hoping to clear the last items pretty quick, but got distracted with the other items we have been discussing.

I will try to get the last two items on this cleared soon.

**Comment by deoren** [comment]
Note to self:

http://www.sphinx-doc.org/en/stable/install.html

> Currently, Python offers two major versions, 2.x and 3.x. Sphinx 1.5 can run under Python 2.7, 3.4, 3.5, 3.6, with the recommended version being 2.7. This chapter assumes you have installed Python 2.7.

Probaby worth adding that Python 2.7 is still the recommended version of Python to use with Sphinx.
