### ISSUE TITLE
Update filters section to emphasize RainerScript format does not have any additional performance impact compared to the "basic" format

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#413]
From https://github.com/rsyslog/rsyslog-doc/issues/391#issuecomment-350514456:

> In the filters section where we are talking about the basic options (including
the ":msg contains" type) we should note that in older versions there were
performance advantages to avoid the advanced versions, but as of v8 there is no
difference.

**Comment by rgerhards** [comment]
> but as of v8 there is no difference.

It's actually since v7. @davidelang

**Comment by davidelang** [comment]
On Sun, 10 Dec 2017, Rainer Gerhards wrote:

>> but as of v8 there is no difference.
>
> It's actually since v7. @davidelang

Ahh, I thought the config optimizer went in early inthe v8 days.

If it was actually in v7, then all distros are shipping something new enough to 
not matter, if it was v8, then we should call it out as there are some distros 
where v7.small is shipped.

**Comment by rgerhards** [comment]
> Ahh, I thought the config optimizer went in early inthe v8 days.

That's right, but that was just an "on top improvement". Pre-v6, we used a different script interpreter, and that one was very slow. Starting with v7, we had a new pretty fast engine. In v7 mail.* was still faster than when you expressed it with an if-condition that contained an and, and this was changed in v8. But v7 is really good to go with the scripting language.

**Comment by deoren** [comment]
Note: While not an update to the filters section, this topic was touched on in a recent update to the config format doc (16b5a8a74da6d3e2da96b0a66c62cb274396270d).

**Comment by deoren** [comment]
> Note: While not an update to the filters section, this topic was touched on in a recent update to the config format doc (16b5a8a).

That said, perhaps that doc should be updated again to specify "Prior to v7" instead of "Prior to v8" as it states now.
