### ISSUE TITLE
update doc generation for website

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-doc#429]
This is in essence currently done via this script (starting in the rsyslog-doc git project clone):
```
rm -rf build
git checkout master
git pull
sphinx-build -b html source build >/dev/null
```
Then, ```build``` directory is rsync'ed over to the actual server.

@deoren how should I modify this script?

**Comment by deoren** [comment]
Are you asking what you need to do to build multiple branches, or to incorporate a newer (non-system) copy of sphinx into the build process?

If the latter, then running `python -m pip install sphinx --user` and then run `python -m pip show sphinx` to confirm what copy of sphinx will be referenced. You can also just run `sphinx-build --version` as the user that will build the docs to confirm what version of sphinx-build will be used.

**Comment by rgerhards** [comment]
> Are you asking what you need to do to build multiple branches, or to incorporate a newer (non-system) copy of sphinx into the build process?

I was under the impression that I needed to run some kind of script instead of just sphinx-build. Did I get this wrong (note: this is the first thing I read this morning, so I may came over a solution in other postings). 

As a side-note I needed to add ```--upgrade``` to the pip install on the system in question. Seems to have done the trick :-)

**Comment by deoren** [comment]
> I was under the impression that I needed to run some kind of script instead of just sphinx-build. Did I get this wrong

I think sphinx-build is smart enough to rebuild changed files, but I don't know how it handles potential orphan files from prior builds. If your concern is automating some of the cleanup steps prior to building then you may need more than just the sphinx-build command, otherwise the `sphinx-build -b html source build` command should do to generate the files.

> As a side-note I needed to add --upgrade to the pip install on the system in question. Seems to have done the trick

What user account (su, sudo or standard non-root, non-sudo) did you use? Sounds like you may have upgraded the system copy of Sphinx. What do you get when running `pip show sphinx`? I am not in front of a PC, but I believe that is the command to show you where a package was installed, what version, etc.

**Comment by rgerhards** [comment]
FYI: the updated happened yesterday, hadn't time to check the site yet.

without --upgrade, pip (in any mode) just told me that the module "is already installed" (which was correct, installed but the old version). --upgrade did just what it tells ;-)

**Comment by deoren** [comment]
Gotcha. If/when you get the time, could you run `pip show sphinx`? It would be good to know whether that command upgraded the existing system copy or if it was "shadowed" by a local install (that pip treats as an upgrade).

Did you run pip with elevated privileges?

No rush on this, just collecting info for future work.

**Comment by rgerhards** [comment]
I ran it with elevated privileges, so I *assume* the system copy should be updated. The cron job runs under my account, FYI.

**Comment by deoren** [comment]
Yeah, most likely the system copy was updated then.

**Comment by deoren** [comment]
Is this still an action item for you? When I  glanced at the http://www.rsyslog.com/doc/master/ content earlier I saw a recent timestamp on the index page.

refs #401

**Comment by rgerhards** [comment]
sry, forgot to close. All seems to be well now :-)
