### ISSUE TITLE
Update (or remove) OptimizeForUniprocessor coverage

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#453]
refs: rsyslog/rsyslog#2280

@rgerhards Should we remove the entire entry for it or add a note indicating that it is no longer supported (like with 613b348bb96594082f6de368c045db3c27697125)? 

I'm guessing that you kept the `$klogLocalIPIF` entry instead of removing it because there was still a usable alternative you wanted to forward readers to, but in this case since the option is no longer supported by _any_ means, what is your preference?

**Comment by rgerhards** [comment]
Did we start a list of things that no longer exist? That would be a good place for it. I think it can be useful if we keep a record of everything that once existed -- especially if someone fights with an old config. That's why I also have not simply removed it from code but turned it to en "no longer exists" error message.

But we should not take any step further than mentioning that it exists, maybe a link to the version where it was present.

**Comment by deoren** [comment]
> @rgerhards: Did we start a list of things that no longer exist? 

Not that I know of. It was an item that came up several times in our discussions, but neither of us have carved out time for it yet. I think one of the things that I was unsure about was the form it would take, whether a separate page or whether a section on the original page where the item appeared just for obsolete content.

> @rgerhards: That would be a good place for it. I think it can be useful if we keep a record of everything that once existed -- especially if someone fights with an old config. 

I can see that.

> @rgerhards: That's why I also have not simply removed it from code but turned it to en "no longer exists" error message.

That part I definitely understand. It's really useful to have the app in question tell you that what you're trying to do is no longer supported.

**Comment by davidelang** [comment]
It is a good thing to not have the phased out config item cause a fatal error, 
but instead only cause a warning.

It shouldn't matter when it was phased out (although the reason for it being 
phased out would be useful, 'use X instead' or 'found to not be an 
optimization')

**Comment by davidelang** [comment]
On Sat, 23 Dec 2017, Deoren Moor wrote:

>> @rgerhards: Did we start a list of things that no longer exist?
>
> Not that I know of. It was an item that came up several times in our 
> discussions, but neither of us have carved out time for it yet. I think one of 
> the things that I was unsure about was the form it would take, whether a 
> separate page or whether a section on the original page where the item 
> appeared just for obsolete content.

I would have it on the page where it originally existed.

**Comment by deoren** [comment]
@rgerhards @davidelang I've updated my PR to mark the directive as no longer supported instead of removing the reference to it entirely. 

I'll keep an eye out for a good place to group "retired" (need a better name?) directives. If we're lucky we can grep the rsyslog source for `eCmdHdlrGoneAway` to identify other directives that are no longer supported for inclusion in the "retired" doc.

**Comment by rgerhards** [comment]
> (although the reason for it being
> phased out would be useful, 'use X instead' or 'found to not be an
> optimization')

It's quite a bit of extra effort as the old config system does not provide that ability. I hope a generic error message is good enough, especially as we should have a list of obsolete config format directives (using the term "directive" now with intent).

**Comment by rgerhards** [comment]
> On Sat, 23 Dec 2017, Deoren Moor wrote:
> > @rgerhards: Did we start a list of things that no longer exist?
> 
>  Not that I know of. It was an item that came up several times in our
>  discussions, but neither of us have carved out time for it yet. I think one of
>  the things that I was unsure about was the form it would take, whether a
>  separate page or whether a section on the original page where the item
>  appeared just for obsolete content.
> I would have it on the page where it originally existed.

I still think we should remove all obsolete format references and just put them into a single old-to-new mapping page. So it'll be removed from where it originally existed. On the new (single) page, we could add them at the bottom as "removed".

For new style/script parameters that disappear, I agree to keep them on the same page.
