### ISSUE TITLE
doc renders "badly" on www.rsyslog.com/doc

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-doc#459]
have a look here: http://www.rsyslog.com/doc/master/configuration/conf_formats.html

I guess that's due to some interaction between sphinx-generated doc and CSS. @deoren @alorbach any idea of how to solve this?

**Comment by deoren** [comment]
@rgerhards I don't have a PC in front of me at the moment to test, but I would guess that the frame the content is embedded within is "squishing" the content. Looking at the docs that I uploaded to a temp location I see the bullets displaying normally. I will try to test and respond back when i can.

**Comment by deoren** [comment]
@rgerhards I'm not a web developer, but I tinkered with the settings for the site using the Google Chrome Developer Tools and toggled some CSS styling off/on until I located what I believe to be the culprit. I took a screenshot with the a specific style disabled to help illustrate where it appears you have a conflict with the chosen WordPress theme:

![rsyslog_master_branch_bullet_display_unexpected_styling_2017-12-25](https://user-images.githubusercontent.com/1550338/34346889-515f594c-e9c2-11e7-8f1d-af8472dc4904.png)

I will defer to others more knowledgeable than I to confirm whether what I've identified is truly the issue.

**Comment by alorbach** [comment]
We can add some hardcoded css within the static manual page generator on rsyslog.com that overrides wordpress related stylesheet issues like @deoren pointed out. 

Someone just needs to go through all issues, and find out which css directive needs to be fixed.

**Comment by rgerhards** [comment]
I think it probably only is the bullet points. And I also don't think we do not need them elsewhere on the site. Could you give it a try and disable the bullet point CSS on the main site?

**Comment by alorbach** [comment]
I have removed it from the CSS, should be shown proberly now:
http://www.rsyslog.com/doc/master/configuration/conf_formats.html

**Comment by rgerhards** [comment]
unfortunately it's not the case, at least for me and with Chrome.  mmmhhhh... mabye it's indeed somthing more complex :-(

**Comment by alorbach** [comment]
I tested it on Chrome. 
The CSS File is properly still cached. For some reason it was also cached on my chrome as well.

**Comment by rgerhards** [comment]
@alorbach my bad, I think the browser cache indeed is it. Thx!

**Comment by rgerhards** [comment]
@deoren could you validate that this is fixed for you as well? If so, I think we can close.

**Comment by deoren** [comment]
@rgerhards I too had a cached stylesheet, but after viewing the http://www.rsyslog.com/doc/master/configuration/conf_formats.html page in a private/incognito window I see that the formatting has been fixed.
