### ISSUE TITLE
"random()" missing from functions list

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#460]
From https://github.com/rsyslog/rsyslog/issues/2224#issuecomment-353779101:

> @rgerhards: actually, random() exists, I think for quite a while. Maybe doc is missing (could not check right now).

Looking at the docs, I don't see it listed:

- http://www.rsyslog.com/doc/v8-stable/rainerscript/functions.html
- http://www.rsyslog.com/doc/master/rainerscript/functions.html

**Comment by deoren** [comment]
If I'm reading the commit logs correctly, it appears that the `random` function was added in rsyslog/rsyslog@4db25fb98bf8f69ad847ae19b5e30aedee31f6fa

**Comment by deoren** [comment]
NVM, I found mention of it even before then in rsyslog/rsyslog@59b46975bde1ac21730ae678935c3537babfbac8

**Comment by deoren** [comment]
```c

/* grammar/rainerscript.c */

static long long
doRandomGen(struct svar *__restrict__ const sourceVal) {
	int success = 0;
	long long max = var2Number(sourceVal, &success);
	if (! success) {
		DBGPRINTF("rainerscript: random(max) didn't get a valid 'max' limit, defaulting random-number "
			"value to 0");
		return 0;
	}
	if(max == 0) {
		DBGPRINTF("rainerscript: random(max) invalid, 'max' is zero, , defaulting random-number value to 0");
		return 0;
	}
	long int x = randomNumber();
	if (max > MAX_RANDOM_NUMBER) {
		DBGPRINTF("rainerscript: desired random-number range [0 - %lld] "
			"is wider than supported limit of [0 - %d)\n",
			max, MAX_RANDOM_NUMBER);
	}
	return x % max;
}
```

@rgerhards I see how the function handles receiving no arguments and 0 as the argument (0 is returned), but I can't understand what is happening when a value is provided larger than the platform supports. I see that the `DBGPRINTF` statement is triggered to log the warning in the debug output, but I don't see where any action is taken to handle the "value too large" situation.

Is this because using the modulus operator is able to safely handle values larger than RAND_MAX (which MAX_RANDOM_NUMBER "points" to)? Is the only concern just logging why `return x % max` is potentially returning unexpected results?

**Comment by rgerhards** [comment]
> @rgerhards I see how the function handles receiving no arguments and 0 as the argument (0 is returned), but I can't understand what is happening when a value is provided larger than the platform supports. I see that the DBGPRINTF statement is triggered to log the warning in the debug output, but I don't see where any action is taken to handle the "value too large" situation.
> 
> Is this because using the modulus operator is able to safely handle values larger than RAND_MAX (which MAX_RANDOM_NUMBER "points" to)? Is the only concern just logging why return x % max is potentially returning unexpected results?

yup, no issue with this

The rest: we cannot abort or do anything else then log it to the debug log. I'd say it would probably be better to log a warning message to the user, albeit this can get a bit chatty. Nevertheless, we should file an issue to change the behavior.

In any case, we should **not** document the specifics that the code currently does, because this is implementation-dependent and not something I want to guarantee for all future. In essence, the function generates a random number potentially in the range from 0..MAX -- that's it. It is worth noting that it is **not** a crypto-grade random number (albeit it sometimes may be, but again, that's an implementation detail we must not expose as an interface).

**Comment by rgerhards** [comment]
I forgot this one:

> return x % max is potentially returning unexpected results?

No even unexpected. It still returns a random number in ```0..max```, BUT in actually it is not may but ```0..MAX_RANDOM_NUMBER < max```. So the number returned will never be in the interval ```MAX_RANDOM_NUMBER..max``` - but it still is random. Mission accomplished ;-)

**Comment by deoren** [comment]
> @rgerhards: The rest: we cannot abort or do anything else then log it to the debug log. I'd say it would probably be better to log a warning message to the user, albeit this can get a bit chatty. Nevertheless, we should file an issue to change the behavior.

I created rsyslog/rsyslog#2424 for this. I based the report off of the discussion here, so it is likely that I may have gotten the details wrong. Please modify the report as you see fit to correct the information.

**Comment by deoren** [comment]
> @rgerhards: In any case, we should not document the specifics that the code currently does, because this is implementation-dependent and not something I want to guarantee for all future. 

Understood. Document the functionality, not the implementation. In this case, I was trying to work backwards from what I found in the source code, so it wasn't entirely clear at first what behavior should be intentionally exposed to the user.

> @rgerhards: In essence, the function generates a random number potentially in the range from 0..MAX -- that's it. It is worth noting that it is not a crypto-grade random number (albeit it sometimes may be, but again, that's an implementation detail we must not expose as an interface).

Alright. The "potentially in the range" bit I am not sure I follow, but I hope that by listing the valid outcomes that it will be once we finish adding coverage for the function.

>> @deoren: return x % max is potentially returning unexpected results?

> @rgerhards: Not even unexpected. It still returns a random number in ```0..max```, BUT in actually it is not ```max``` but ```0..MAX_RANDOM_NUMBER < max```. So the number returned will never be in the interval ```MAX_RANDOM_NUMBER+1..max``` - but it still is random. Mission accomplished ;-)

So if I understand you, the returned value will be either 0 or in the the range of values between 0 and `max`, it just may not use values *all the way up to `max`* due to platform limitations.

**Comment by rgerhards** [comment]
In a community meeting, but quick info:
The original intent for random was too use it for load balancing, so max
was usually very low.

Sent from phone, thus brief.

Am 21.01.2018 18:50 schrieb "Deoren Moor" <notifications@github.com>:

**Comment by deoren** [comment]
> @rgerhards: In a community meeting, but quick info:
> The original intent for random was too use it for load balancing, so max was usually very low.

Thanks. I've reworked the coverage slightly in an attempt to cover all points, but without detail too great to get in the way.
