### ISSUE TITLE
Forwarding log files with file names when we use wildcards

### ISSUE THREAD

**Issue by roshu10** [rsyslog/rsyslog-doc#474]
I'm using wildcard to send logs to remote server, But not able forward log files with file names. All logs from multiple files are being dumped to single file. 

Is there any way to get the original file names in Syslog ?

**rsyslog client config file:**
```
module(load="imfile" mode="inotify") #needs to be done just once
input(type="imfile"
      File="/var/lib/docker/volumes/httpd_logs-br/_data/*.log"
      Tag="tag2_"
      addMetadata="on"
      Severity="notice"
      Facility="local7")
```
**rsyslog server config file**
```
input(type="imptcp" port="18039" ruleset="br_access_logs_rule")
template(name="br_access_logs" type="string" 
                string="/logs/central/%HOSTNAME%/%programname%.log")
ruleset(name="br_access_logs_rule"){
      action(type="omfile" DynaFile="br_access_logs") stop
}
```

Thanks for any help !!

**Comment by rgerhards** [comment]
Let me try it relatively brief first:

You need to transmit the file name to the remote end:

1. enable metadata inside imfile: http://www.rsyslog.com/doc/master/configuration/modules/imfile.html
1. you now need to craft a custom template that includes the filename metadata (```$!metadata!filename```)
1. you need to apply this template to the forwarding action

On the receiver:

1. you need to extract the metadata again (e.g. via mmjsonparse)
1. now you can use that file name as any other variable

We need to do a writeup of a full scenario, unfortunately I do not have time at the moment. I hope this get's you going or some others will also jump in.

**Comment by roshu10** [comment]
@rgerhards 

I have did some changes on rsyslog-client
module(load="imfile" mode="inotify") #needs to be done just once

# http://www.rsyslog.com/doc/relp.html
module(load="omrelp")

ruleset(name="sendToLogserver") {
    action(type="omrelp" Target="172.16.216.118" Port="18039" Template="LongTagForwardFormat")
}

# Sending files using wildcard characters
input(type="imfile"
      File="/var/lib/docker/volumes/httpd_logs-br/_data/*.log"
      Tag="tag2_"
      addMetadata="on"
      Ruleset="myapp_logs"
      Severity="notice"
      Facility="local7")

ruleset(name="myapp_logs") {
        set $.suffix=re_extract($!metadata!filename, "(.*)/([^/]*)", 0, 2, "all.log");
        call sendToLogserver
}


Still it's not working though

**Comment by davidelang** [comment]
what does the template LongTagForwardFormat look like? does it include the 
filename?

**Comment by roshu10** [comment]
This is the complete file:

module(load="imfile" mode="inotify") #needs to be done just once

module(load="omrelp")

template (name="LongTagForwardFormat" type="string"
string="<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%$.suffix%%msg:::sp-if-no-1st-sp%%msg%")

ruleset(name="sendToLogserver") {
    action(type="omrelp" Target="172.16.216.118" Port="18039" Template="LongTagForwardFormat")
}

# Sending files using wildcard characters
input(type="imfile"
      File="/var/lib/docker/volumes/httpd_logs-br/_data/*.log"
      Tag="tag2_"
      addMetadata="on"
      Ruleset="myapp_logs"
      Severity="notice"
      Facility="local7")

ruleset(name="myapp_logs") {
        set $.suffix=re_extract($!metadata!filename, "(.*)/([^/]*)", 0, 2, "all.log");
        call sendToLogserver
}

**Comment by selivan** [comment]
And please also post the full server config. You wrote in Disqus comments, that you changed server module to "omrelp", but it should be "imrelp", if you are trying to get log, not send them.

Let's debug this step by step:

 - try `nc <server ip> 18039` on clent to check, if network connectivity is OK.
 - try writing logs to local file on client and see what appears in it
 - try stopping server and using `nc -l -p 18039` to see, what data is transferred to server

**Comment by deoren** [comment]
@roshu10 Are you still having this issue? Have you tried the steps that @selivan provided?

**Comment by roshu10** [comment]
tried, rsyslog-client is not sending the data to rsyslog-server

**Comment by selivan** [comment]
@roshu10 That means, it doesn't get them locally. Do it have read permissions on `/var/lib/docker/volumes/httpd_logs-br/data/*.log`, and execute permissions on all folders along the way? rsyslog usually runs as `syslog` user, an docker often runs everything inside as root.

You may try debugging by steps:
* Make it read logs from single log file in `var/lib/docker/volumes/httpd_logs-br/data/` and write it to local file again. Probably, you'll get some errors on this step.
* Make it read multiple log files from required location, and write it to single local file.
* Make it read multiple log files from required location, and write it to multiple local files(trick with metadata)
* Make it send this over network.

**Comment by roshu10** [comment]
I tried, still its not working

**Comment by selivan** [comment]
@roshu10 It can not even forward logs from single local file to other local file? Then 99% problem is in permissions.

**Comment by str1k3r** [comment]
@roshu10 check that destination folder is writable for syslog:adm

**Comment by Skull0ne** [comment]
everything under /var/lib/docker/ is almost 700 and usually rsyslog is running as syslog so it's not able to parse those directories.

for the moment i removed : "$PrivDropToUser syslog" and "$PrivDropToGroup syslog" from my configuration to be able to send kubernetes logs under /var/log/containers (all logs in that directory are links to /var/lib/docker/containers/$DOCKER_ID/$DOCKER_ID-json.log)

it's dirty, but if it can help you

**Comment by selivan** [comment]
@Skull0ne less dirty approach would be to set unix acl and default acl on required directory to allow syslog user read access.

**Comment by Skull0ne** [comment]
@selivan already thought about that but it's not working (i think) beceause if i set the acl for /var/lib/docker/containers, syslog still won't be able to look insible /var/lib/docker/containers/* (and i can't set acl again each time a pod restarts or if a new one is deployed)

**Comment by selivan** [comment]
@Skull0ne that's what default ACLs are for: you set default ACL on /var/lib/docker/containers, and it is automatically applied to every new file or directory created inside it. Of course, you still need to recursively set ACLs on files and directories that are already there.

**Comment by Skull0ne** [comment]
@selivan ok thanks i will check that point later! 👍 

does someone was able to make the asked configuration works?

since i configured the ruleset i'm not able to get my log on my receiver :
`set $.suffix=re_extract($!metadata!filename, "(.)/([^/])", 0, 2, "all.log");`

**Comment by selivan** [comment]
@Skull0ne this looks a lot like a configuration from my article on rsyslog: https://selivan.github.io/2017/02/07/rsyslog-log-forward-save-filename-handle-multi-line-failover.html and it works for me at least on two different projects and other project I'm not involved but I know it works there.

May be we better discuss it in it's comments than in rsyslog bug tracker. At least, show your configuration. The string you'v shown is not a complete ruleset.

**Comment by Skull0ne** [comment]
client config :
`module(load="imfile" mode="inotify")
module(load="mmjsonparse")

action(type="mmjsonparse")

ruleset(name="k8s") {
        set $.suffix=re_extract($!metadata!filename, "(.)/([^/])", 0, 2, "all.log")
}

input(type="imfile"
      file="/var/log/containers/*.log"
      tag="k8s"
      ruleset="k8s"
      addmetadata="on"
      Severity="info"
      Facility="local6")

*.* action(type="omrelp"
           target="$server"
           port="514")
`

receiver config (i know that i will have to work on that part once i will receive the log, it's working without the ruleset) : 
`template(name="KubernetesLogFormat" type="string"
        string="%msg:2:$%\n")
template(name="KubernetesLog" type="string"
	string="/srv/log/%HOSTNAME%/kubernetes/%$YEAR%/%programname:$%/pods-log.%$YEAR%%$MONTH%%$DAY%")
if $syslogfacility-text == 'local6' and $syslogseverity-text == 'info' then -?KubernetesLog;KubernetesLogFormat
& stop
`

**Comment by selivan** [comment]
@Skull0ne your ruleset has exactly one rule - it sets local variable. And then it does nothing. Input from /var/log/containers/*.log calls it, sets the local variable and then does nothing.

For old-style syslog syntax, like 
```
*.info /log/info
*.auth /log/auth
```
all this rules were part of one big default RuleSet, and each log was processed by all of them. You had to explicitly say if you want to stop processing logs that matched some rule.

For modern syntax, each input calls it's own RuleSet. Default RuleSet still exists for compatibility reasons, but if you call RuleSet for Input explicitly, it is not applied.

**Comment by Skull0ne** [comment]
@selivan  your wiki is great but i have a last issue : i receive my logs into /$PATH/$.logpath/pods.log but i also have a $PATH/pods.log which has the content of all my $.logpath/pods.log 

sender : 
```module(load="imfile" mode="inotify")
module(load="mmjsonparse")

action(type="mmjsonparse")

ruleset(name="k8s") {
        set $.suffix=re_extract($!metadata!filename, "(.*)/.*_([^/]*)_.*", 0, 2, "all.log");
        call sendToLogserver
}
# I had to modify your regex to get kubernetes namespaces, that part works

input(type="imfile"
      file="/var/log/containers/*.log"
      tag="k8s__"
      ruleset="k8s"
      addmetadata="on"
      Severity="info"
      Facility="local6")

template (name="LongTagForwardFormat" type="string"
	string="<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%$.suffix%%msg:::sp-if-no-1st-sp%%msg%")

ruleset(name="sendToLogserver") {
	action(type="omrelp"
           target="$server"
           template="LongTagForwardFormat"
           port="514")
}
```

receiver : 
```template(name="OnlyMsg" type="string" string="%msg:::drop-last-lf%\n")

template(name="KubernetesLogFormat" type="string"
        string="%msg:2:$%\n")

template(name="KubernetesLog" type="list") {
         constant(value="/srv/log/")
         property(name="hostname")
         constant(value="/kubernetes/")
         property(name="timegenerated" dateFormat="year")
         constant(value="/")
         property(name="$.logpath")
         constant(value="/pods.log")
	}
if $syslogfacility-text == 'local6' and $syslogseverity-text == 'info' and $programname startswith 'k8s' 
then {
	-?KubernetesLog;KubernetesLogFormat
	set $.logpath = replace($programname, "k8s__", "");
	action(type="omfile" dynaFile="KubernetesLog" template="OnlyMsg")
	stop
}```

and as result : 
```
[root@receiver:/etc/rsyslog.d]# ls -l /srv/log/sender/kubernetes/2018/*
-rw-r----- 1 syslog adm    36160 Jun  7 20:22 /srv/log/sender/kubernetes/2018/pods.log

/srv/log/sender/kubernetes/2018/kube-system:
total 36
drwx------ 2 syslog syslog  4096 Jun  7 20:15 ./
drwxr-xr-x 4 syslog syslog  4096 Jun  7 20:15 ../
-rw-r--r-- 1 syslog syslog 25571 Jun  7 20:22 pods.log

/srv/log/sender/kubernetes/2018/test-namespace:
total 20
drwx------ 2 syslog syslog  4096 Jun  7 20:15 ./
drwxr-xr-x 4 syslog syslog  4096 Jun  7 20:15 ../
-rw-r--r-- 1 syslog syslog 10762 Jun  7 20:15 pods.log
```

thanks for the help & i hope it will help someone else

**Comment by Skull0ne** [comment]
@selivan i configured my acl to grant access to /var/lib/docker/containers/* to syslog user. when i log as syslog i'm able to read my log files, but when i configurer rsyslog to run as syslog it's not able to do it. i also tried to stop apparmor to be sure

```
$PrivDropToUser syslog
$PrivDropToGroup syslog
```

```
root@:~# getfacl /var/lib/docker/
getfacl: Removing leading '/' from absolute path names
# file: var/lib/docker/
# owner: root
# group: root
user::rwx
user:syslog:r-x
group::--x
group:adm:r-x
group:syslog:r-x
mask::r-x
other::--x

root@:~# getfacl /var/lib/docker/containers
getfacl: Removing leading '/' from absolute path names
# file: var/lib/docker/containers
# owner: root
# group: root
user::rwx
user:syslog:r-x
group::---
group:adm:r-x
group:syslog:r-x
mask::r-x
other::---

root@:~# getfacl /var/lib/docker/containers/DOCKER_ID/
getfacl: Removing leading '/' from absolute path names
# file: var/lib/docker/containers/DOCKER_ID/
# owner: root
# group: root
user::rwx
user:syslog:r-x
group::---
group:adm:r-x
group:syslog:r-x
mask::r-x
other::---
default:user::rwx
default:user:syslog:r-x
default:group::---
default:group:adm:r-x
default:group:syslog:r-x
default:mask::r-x
default:other::---

root@:~# getfacl /var/lib/docker/containers/DOCKER_ID/DOCKER_ID-json.log 
getfacl: Removing leading '/' from absolute path names
# file: var/lib/docker/containers/DOCKER_ID/DOCKER_ID-json.log
# owner: root
# group: root
user::rw-
group::r--
other::r--
```

```
rsyslogd-2433: file '/var/log/containers/default-http-backend-2250134485-3c78s_kube-system_default-http-backend-c8723f65a7a7371374037d7d99abb99ac07d977c792edd79add695392853ba22.log': open error: Permission denied [v8.35.0 try http://www.rsyslog.com/e/2433 ]
```

**Comment by selivan** [comment]
@Skull0ne 

```
root@:~# getfacl /var/lib/docker/containers/DOCKER_ID/DOCKER_ID-json.log 
getfacl: Removing leading '/' from absolute path names
# file: var/lib/docker/containers/DOCKER_ID/DOCKER_ID-json.log
# owner: root
# group: root
user::rw-
group::r--
other::r--
```

This output indicates that `/var/lib/docker/containers/DOCKER_ID/DOCKER_ID-json.log` does not have any ACLs for syslog user. Probably it was created before `/var/lib/docker/containers/DOCKER_ID/` was set default ACL. But anyway it's world readable.

> when i log as syslog i'm able to read my log files, but when i configurer rsyslog to run as syslog it's not able to do it

That's weird. What command did you use to switch user?

Try to switch to syslog user: `sudo -u syslog -H /bin/bash` and the check access to all the directories along the way to log file:

```
ls /var
ls /var/lib
...
ls /var/lib/docker/containers/DOCKER_ID/DOCKER_ID-json.log
```

And try using direct file name in syslog config instead of symlink (that probably won't help, but we may see some diagnostic messages).

**Comment by selivan** [comment]
@Skull0ne 

Default ACL for directory means that all files and directories created inside it will get that ACL and (for directories) that default ACL. Default ACL for files would not have any meaning, you can not create files inside files. So what you need is:

  * once set recursively default ACL for directory and all it's sub-directories
  * once set recursively ACL for all already existing files inside that directory and it's sub-directories

Or just once set default ACL for an empty directory and then create required sub-directories and files inside it.

After that, all files and directories created in that directory and it's sub-directories will have required ACL(and default ACL for directories).

**Comment by riturajb** [comment]
I am using the same config on the client and server side. Still not able to see the logs. Please can you tell me how do I debug by sending logs to local file (as mentioned in a comment above in the thread). 
I have made sure the default acl is set and also manually I have changed the ACL for the existing files to syslog user.

My client config is:
###########
```
input(type="imfile"
      File="<client-log-dir>/*.log"
      Tag="myapp__"
      Ruleset="myapp_logs"
      addMetadata="on"
      Severity="info"
      Facility="local3"
     )


ruleset(name="myapp_logs") {
    # http://www.rsyslog.com/doc/v8-stable/rainerscript/functions.html
    #   # re_extract(expr, re, match, submatch, no-found)
    set $.suffix=re_extract($!metadata!filename, "(.*)/([^/]*)", 0, 2, "all.log");
                        call sendToLogserver
                        }


template (name="LongTagForwardFormat" type="string"
        string="<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%$.suffix%%msg:::sp-if-no-1st-sp%%msg%")

ruleset(name="sendToLogserver") {
        action(type="omrelp"
           target="<server-ip>"
           template="LongTagForwardFormat"
           port="5938")
}

```
##############################
Server config is:

```
template(name="ApiLog" type="list") {
    constant(value="/<log-dir>/")
#    property(name="fromhost-ip")
#    constant(value="/")
#    property(name="timegenerated" dateFormat="year")
#    constant(value="-")
#    property(name="timegenerated" dateFormat="month")
#    constant(value="-")
#    property(name="timegenerated" dateFormat="day")
#    constant(value="/")
    property(name="$.logpath" )
}

template(name="OnlyMsg" type="string" string="%msg:::drop-last-lf%\n")

if $syslogfacility-text == 'local3' and $syslogseverity-text == 'info' and $programname startswith 'myapp'
then {
        set $.logpath = replace($programname, "myapp__", "");
        action(type="omfile" dynaFile="ApiLog" template="OnlyMsg")
        stop
}
```
#############

**Comment by rgerhards** [comment]
folks, are you all jumping on the same thread with different detail questions?

**Comment by selivan** [comment]
@rgerhards I am sorry, this issue looks to be support thread for my article https://selivan.github.io/2017/02/07/rsyslog-log-forward-save-filename-handle-multi-line-failover.html

I suggest to close this issue and all who have questions are welcome to comments section in my blog.

**Comment by selivan** [comment]
@riturajb To send logs to local file for debug, just change sendToLogserver ruleset:

```
ruleset(name="sendToLogserver") {
        action(type="omfile"
           File="/var/log/my-debug.log"
           template="LongTagForwardFormat"
           )
}
```

And don't forget to run `rsyslogd -N 1 ` to check that config is correct.

**Comment by rgerhards** [comment]
> I suggest to close this issue and all who have questions are welcome to comments section in my blog.

No problem, I just begun to go crazy on what to do with the issue ;-)

Folks please go to https://selivan.github.io/2017/02/07/rsyslog-log-forward-save-filename-handle-multi-line-failover.html if your questions arise from there. Thx a ton. If not, please create a new focussed issue.
