### ISSUE TITLE
release process: need way to specify version number

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-doc#482]
The improvements to the doc generation now generate a hash-based version number. That is great for devel releases, but we need to find a way to use the regular version number (e.g. "8.32.0") for release builds.

**Comment by deoren** [comment]
@rgerhards

From the first [build script](https://github.com/deoren/rsyslog-examples/blob/master/scripts/build_docs.sh) that I used:

```bash
version=$(grep -E '^version' source/conf.py | awk '{print $NF}' | sed "s/'//g")
datestamp=$(date '+%Y%m%d')
commit=$(git describe | awk -F'-' '{print $NF}')
release="${version}.${datestamp}.${commit}"

declare -a formats
formats=(
  epub
  html
)

for format in "${formats[@]}"
do
    sphinx-build -D version="$version" -D release="$release" -b $format source build
done
```

I eventually worked that into the `build.sh` script with the idea that someone could run that script whenever needed to generate fresh docs from all branches. It ended up growing in a different direction than originally intended when I made the mistaken assumption that the `release_build.sh` script could be supplanted by a modified `build.sh` script that did everything both of the original scripts did.

An earlier form of the combined script actually did work well enough for that, but then I started work to get the script into shape for automation. My thoughts at the time were that the `build.sh` script could be used on a build server to periodically generate fresh copies of all branches *and* generate a tarball that could be used for official stable releases.

I *meant* to follow up with you about setting up such an automated build process, but again I made the mistake of assuming that there was a different/official process for releasing the stable doc tarball outside of the repo. That proved to be false and on hindsight wasn't a good assumption (it makes sense to keep the scripts in the repo and use an include mechanism for anything sensitive).

I'll submit a PR for a small tweak to the `release_build.sh` script that references a script argument for setting the version info.

On a related note, I've setup such an automated build process on one of my VPS boxes in an effort to help with sharing prototype changes as I work on PRs. I've not yet provided a PR for the `/etc/cron.d/rsyslog-doc` or `/usr/local/sbin/rsyslog-doc.sh` files, but plan to do so once I let the process run for a while longer. At that point setting up a `contrib/scripts` dir might be the way to go.

**Comment by deoren** [comment]
@rgerhards I forgot to clarify in the last response: That small script example uses a hash-based version numbering for the builds, but shows via the `sphinx-build` calls how to go about using a stable version number via `sphinx-build` command-line options.

**Comment by davidelang** [comment]
can we use git describe for this?

**Comment by deoren** [comment]
@davidelang That is an option too. I assumed that @rgerhards wanted to keep with a very simple approach for the script in case he builds directly from v8-stable instead of from a tag, but I could be assuming wrong.

**Comment by deoren** [comment]
> @deoren: @davidelang That is an option too. I assumed that @rgerhards wanted to keep with a very simple approach for the script in case he builds directly from v8-stable instead of from a tag, but I could be assuming wrong.

Sorry, I thought you were commenting on my PR and not the issue @rgerhards opened. I wasn't paying close attention when I responded (re context of simple script change).
