### ISSUE TITLE
Regen v8-stable branch, push to rsyslog.com

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#496]
The current v8-stable doc content on rsyslog.com lists 8.33 as the number along with dev build details. I'm actually OK with the build details displaying, but the +1 than current version number is likely to be confusing to some.

> rsyslog 8.33-20180112-f13323d documentation

Ref: http://www.rsyslog.com/doc/v8-stable/

**Comment by deoren** [comment]
@rgerhards Just making sure you saw this one.

**Comment by rgerhards** [comment]
Yeah, I saw this, but fixing would require backporting the fix from master to 8.32.0 (v8-stable). I personally don't think it is that important, as in ~4 weeks from now that will resolve itself (and probably really nobody notices).

**Comment by rgerhards** [comment]
No, keep it. It has the 8.33 milestone, this ensure we do not forget to check on release.
