### ISSUE TITLE
cron_build_all_branches does not work on Alpine Linux

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-doc#524]
* it requires bash, which is not enabled by default on Alpine
* if bash is installed, it fails on some sort option, albeit the rest of the build seems to succeed, but...
* it fails at the end as follows:
```
build succeeded.
tar: build.sh: No such file or directory
tar: error exit delayed from previous errors
[!] tarball creation failed for  tag ... aborting
/rsyslog-doc # 
```

Also, during build there are many warnings, which otherwise do not appear when the branches are build. Not sure if that is correct or an Alpine-induced problem.

related: https://github.com/rsyslog/rsyslog-doc/pull/523

**Comment by deoren** [comment]
@rgerhards thanks for the report. 

> `tar: build.sh: No such file or directory`

I'm guessing this is for the v8-stable branch?

The v8-stable copy of the script still references the `build.sh` script:

`tar -czf $output_dir/$doc_tarball source build LICENSE README.md build.sh`

Current master does not:

`tar -czf $output_dir/$doc_tarball source build LICENSE README.md`

When I first included that entry the idea was that the stable release tarballs could be automated so that when you got ready to release one you could just fetch it from the build system and deploy it. I've realized that building tarballs via the cron script is probably just a waste of time and lengthens the build process.

**Comment by deoren** [comment]
> if bash is installed, it fails on some sort option, albeit the rest of the build seems to succeed, but...

I wonder if the sort binary is provided by busybox? From what I recall the `sort` call is done to line up the git tags in order so that the latest one can be plucked from the list. I may be able to reliably get the latest tag available through another means without falling back to `sort` to achieve it.

`~/dev/rsyslog/rsyslog-doc$ git describe --tags`
```
v8.32.0-54-g315fcde
```

That *seems* to work, but I've not tested it in practice to determine whether it's reliable.

**Comment by rgerhards** [comment]
@deoren I just wanted to make you aware of the issue. I think it can probably simply be "resolved" by documenting it. I tend to think that most folks will probably need to add some tweaks to cron scripts, so I am not sure how frequently it will be used.

**Comment by deoren** [comment]
> @rgerhards: Also, during build there are many warnings, which otherwise do not appear when the branches are build. Not sure if that is correct or an Alpine-induced problem.

I'll try to replicate that using the docker setup you created for the docs. If nothing else it will give me some additional practice using docker.

> @rgerhards: I just wanted to make you aware of the issue. 

Thank you, I appreciate that.

> @rgerhards: I think it can probably simply be "resolved" by documenting it. I tend to think that most folks will probably need to add some tweaks to cron scripts, so I am not sure how frequently it will be used.

Based on conversation on another ticket, the cron script may go away at some point entirely, but for now (provided you're ok with it) I'll keep it and make enough refinements that it's easy to configure and relatively easy to use. I'll keep using it for a time for the work that I do if nothing else. I believe that documenting it is needed and will do so along with the next PR that I provide for it.

**Comment by rgerhards** [comment]
> Based on conversation on another ticket, the cron script may go away at some point entirely, but for now (provided you're ok with it) I'll keep it and make enough refinements that it's easy to configure and relatively easy to use. I'll keep using it for a time for the work that I do if nothing else. I believe that documenting it is needed and will do so along with the next PR that I provide for it.

I think there are still use cases for it. For example, I still use the old cron script to update the rsyslog.com site. I even modified it a bit. It just does fewer things (checkout - build - push) and the push stage is very env-specific. I am only interested in building v5-stable, v8-stable and master right now, so anything else is not of real interest for me or the main site.

**Comment by rgerhards** [comment]
> I'll try to replicate that using the docker setup you created for the docs. If nothing else it will give me some additional practice using docker.

probably the easiest way is:
```
$ docker run  -vrsyslog-doc:/rsyslog-doc rsyslog/rsyslog_doc_gen git-clone
$ docker run -ti  -vrsyslog-doc:/rsyslog-doc rsyslog/rsyslog_doc_gen bash
[you are now in Alpine's ash, inside the container]
/rsyslog-doc # cd /rsyslog-doc
/rsyslog-doc # chmod +x cron_build_all_branches.sh  (just noticed +x is missing in git!)
/rsyslog-doc # ./cron_build_all_branches.sh 
/bin/ash: ./cron_build_all_branches.sh: not found
(aha, we do not have bash, so let's install it)
/rsyslog-doc # apk add -U bash
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/2) Installing pkgconf (1.3.10-r0)
(2/2) Installing bash (4.4.12-r2)
Executing bash-4.4.12-r2.post-install
Executing busybox-1.27.2-r6.trigger
OK: 77 MiB in 30 packages
/rsyslog-doc # ./cron_build_all_branches.sh 
(now it runs...)
...later: press <ctl>-d to exit the container
$ docker rm -f rsyslog-doc # remove the volume, we do no longer need it / docker system prune
```

**Comment by deoren** [comment]
> @rgerhards: I think there are still use cases for it. For example, I still use the old cron script

Is that one of your own or a modified version of the `release_build.sh` script?

**Comment by deoren** [comment]
> @rgerhards: probably the easiest way is ...

Thanks for those notes. I will give it a shot.

**Comment by rgerhards** [comment]
It's a very basic script that does all I need:
```
docker pull rsyslog/rsyslog_doc_gen # get fresh version
export DOC_HOME=/home/rger/rsyslog-doc
cd $DOC_HOME

echo "**** v5-stable ****"
rm -rf build
git checkout v5-stable
git pull
docker run -ti --rm \
        -u `id -u`:`id -g` \
        -e STRICT="" \
        -e SPHINX_EXTRA_OPTS="-q" \
        -v "$DOC_HOME":/rsyslog-doc \
        rsyslog/rsyslog_doc_gen
rsync ...

echo "**** v7-stable ****"
rm -rf build
git checkout v7-stable
git pull
docker run -ti --rm \
        -u `id -u`:`id -g` \
        -e STRICT="" \
        -e SPHINX_EXTRA_OPTS="-q" \
        -v "$DOC_HOME":/rsyslog-doc \
        rsyslog/rsyslog_doc_gen
rsync ...

echo "**** v8-stable ****"
rm -rf build
git checkout v8-stable
git pull
docker run -ti --rm \
        -u `id -u`:`id -g` \
        -e STRICT="" \
        -e SPHINX_EXTRA_OPTS="-q" \
        -v "$DOC_HOME":/rsyslog-doc \
        rsyslog/rsyslog_doc_gen
rsync ...

echo "**** master ****"
rm -rf build
git checkout master
git pull
docker run -ti --rm \
        -u `id -u`:`id -g` \
        -e SPHINX_EXTRA_OPTS="-q" \
        -v "$DOC_HOME":/rsyslog-doc \
        rsyslog/rsyslog_doc_gen
rsync ...
```
As you can see, nothing fancy, but fast and easy to maintain by anybody over here ;-) I've obfuscated the sync-to-web part.

**Comment by deoren** [comment]
@rgerhards thanks for sharing. This was another good reminder that spinning up a docker container as needed, vs spinning up a long lived session (with a cron script inside), can be useful as a one-shot tool, especially in re to repeoducible builds.

**Comment by deoren** [comment]
```
ubuntu@ubuntu-1404-virtual-machine:/tmp$ sudo docker run -ti -v rsyslog-doc:/rsyslog-doc rsyslog/rsyslog_doc_gen bash`
You are now in Alpine's ash
/home/appliance # apk add -U bash
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/2) Installing pkgconf (1.3.10-r0)
(2/2) Installing bash (4.4.12-r2)
Executing bash-4.4.12-r2.post-install
Executing busybox-1.27.2-r6.trigger
OK: 77 MiB in 30 packages
/home/appliance # sort --help
BusyBox v1.27.2 (2017-11-28 16:17:30 GMT) multi-call binary.

Usage: sort [-nrugMcszbdfiokt] [-o FILE] [-k start[.offset][opts][,end[.offset][opts]] [-t CHAR] [FILE]...

Sort lines of text

	-o FILE	Output to FILE
	-c	Check whether input is sorted
	-b	Ignore leading blanks
	-f	Ignore case
	-i	Ignore unprintable characters
	-d	Dictionary order (blank or alphanumeric only)
	-g	General numerical sort
	-M	Sort month
	-n	Sort numbers
	-t CHAR	Field separator
	-k N[,M] Sort by Nth field
	-r	Reverse sort order
	-s	Stable (don't sort ties alphabetically)
	-u	Suppress duplicate lines
	-z	Lines are terminated by NUL, not newline
```

Yep, hello busybox. No proof yet that is the culprit, but it's likely I'm using an option that isn't compatible. Thank you again for the docker notes.

I'll submit a one-off PR soon to fix the sort command issue.

**Comment by deoren** [comment]
> @rgerhards: `/rsyslog-doc # chmod +x cron_build_all_branches.sh  (just noticed +x is missing in git!)`

That was somewhat intentional. I initially (unintentionally) left the execute bit off, caught it later but opted to leave it off since running the script could be destructive if accidentally triggered. Instead it can be manually set or called via `bash ./cron_build_all_branches.sh`.

I was hoping that would make the script a bit safer.

**Comment by deoren** [comment]
I merged a fix for the sort error to master. If a bash dependency is acceptable then that is resolved, if not then I may need to evaluate what I am using that is bash specific so it can be converted to ash where possible.

The tar warning/error re a missing build.sh file is because the change in master to remove attempts to include that file haven't been merged to v8-stable yet. I think whenever I changed the name of the cron script I failed to also update the tar call to reflect the new name (or as we did in master, remove the file reference).

**Comment by rgerhards** [comment]
I think it is no real problem that the script needs bash, but we should document it. At this stage, I do not plan to add bash to the standard docker image, as in almost all cases it is not required - the cron script is probably used only in a very small fraction of the container incarnations. In those cases, a user can

1. install bash right before running the script
2. base a new container on the existing one where this is added

Actually, we can do 2. at ease if there is demand. So I would say let everything be as-is and wait for complaints. Complaints are IME always a good way to learn what really is needed. Else you spend too often too much time on things that nobody really wants. Been through this far too often...

**Comment by deoren** [comment]
> @rgerhards: So I would say let everything be as-is and wait for complaints. Complaints are IME always a good way to learn what really is needed. Else you spend too often too much time on things that nobody really wants. Been through this far too often...

Good suggestion. "Premature optimization" comes to mind and I'm guilty of that more often than I care to admit.

I plan to move the cron script out of the main directory and therefore out of someone's immediate attention if they go to explore the contents of this repo. I will likely submit a PR soon that moves it into a "contrib" directory that sits alongside the `source` directory.

**Comment by deoren** [comment]
@rgerhards I just took another look in the `tools` directory and at the README file there. It sounds based on the wording that I should probably move the cron script there instead. I saw this of course after I went ahead and created the contrib directory and moved the cron script there. ;)

I'll go ahead and submit a PR anyway based off of that branch, but feel free to reject it if you'd rather the content be placed in the tools directory instead.

**Comment by rgerhards** [comment]
I merged, but would not object if you change again. IMHO, ```tools``` is "officially supported" whereas ```contrib``` is "contributor supported" (as you wrote). So I would think two different directories  is good.

**Comment by deoren** [comment]
> @rgerhards: I merged, but would not object if you change again. IMHO, tools is "officially supported" whereas contrib is "contributor supported" (as you wrote). So I would think two different directories is good.

Sounds good. I'll go ahead and consider this resolved for now then.
