### ISSUE TITLE
TODO: Confirm that sufficient explanation is given for the -Nx config validation options

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#530]
For example, I've seen `-N2` used and I constantly use `-N6` myself based on something I read *somewhere*, but I don't recall where. I assume that the larger number means an increase in verbosity and additionally an increase in the number of checks/thoroughness of checks performed, but I don't know that for sure.

I've been meaning to go back over the docs to make sure there is a good explanation, so this ticket is a reminder for me to do so and update the docs (with help) if the coverage is light.

**Comment by rgerhards** [comment]
I've done a quick code review. Doc update PR immanent.

**Comment by deoren** [comment]
@rgerhards Thanks. I merged the PR, and *then* realized that you might not have been finished with it. My apologies if that was the case.

**Comment by rgerhards** [comment]
no, all is well. I'd assigned the WiP tag otherwise. It's really not more to be said (I think).
