### ISSUE TITLE
Consider shortening version/release build string for dev builds

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#537]
See also: #535, #482, #493 (recent detailed discussion)

Concerns: 

- The string is too long when using the `better` theme or with any theme that places the build string in a prominent location in the docs

Current result:

- rsyslog `8.33-master-20180203-8d3b5a6` documentation

**Comment by deoren** [comment]
The dynamic portion can be updated to reflect whatever we like and we can also modify the static trailing portion of the string as well so that 'documentation' is omitted (perhaps it's just stating what we already know?). If not omitted, perhaps shortened to 'docs' ?

I personally find the current stable + 1 version useful (8.32 stable + 1 = 8.33 *next* stable), as I do the commit and the date. Perhaps this would be useful?

```diff
-rsyslog 8.33-master-20180203-8d3b5a6 documentation
+rsyslog 8.33-master-feb3-8d3b5a6 docs
```

Not a massive difference, but it keeps all current values, though in a shortened form. If it needs trimming even further, this could also work:

```diff
-rsyslog 8.33-master-20180203-8d3b5a6 documentation
+rsyslog 8.33-master-8d3b5a6 docs
```

While I would miss the date, having the commit clearly visible still helps a lot with identifying the build.

Yet another option is to setup the release string shown prominently in the docs this way:

```diff
-rsyslog 8.33-master-20180203-8d3b5a6 documentation
+rsyslog pre-release docs
```

and then retain the dev build release string that I added to the main index page not all that long ago:

![dev_build_info_index_page_current_master_2018-02-03](https://user-images.githubusercontent.com/1550338/35772425-2b4cd8ea-0904-11e8-885e-8bac6cbac991.png)

That will allow us to identify the dev build details without prominently displaying them.

Let me know what you prefer and I'll get it done.

**Comment by rgerhards** [comment]
> The string is too long when using the better theme

I thinks this is not really a "better" theme issue. I just noticed it only when I used that theme because previously the doc was simply unreadable to me on mobile devices (not in a strictly technical sense, but w/ 2-3 words per line I had no interest at all to look at it ;-).

Just want to say I consider this a general issue, **not** theme related.

**Comment by rgerhards** [comment]
more or less for my own ref, this is also an issue on the PC if looked at closely:

http://www.rsyslog.com/doc/master/installation/install_from_source.html

**Comment by rgerhards** [comment]
> Yet another option is to setup the release string shown prominently in the docs this way:
> 
> -rsyslog 8.33-master-20180203-8d3b5a6 documentation
> +rsyslog pre-release docs
> and then retain the dev build release string that I added to the main index page not all that long ago

I think this is an excellent idea, but would prefer a slight change in the name. How about
```
-rsyslog 8.33-master-20180203-8d3b5a6 documentation
+rsyslog 8.33-pre docs
```
That's very short, but still conveys a good idea of which version it is close to (even if someone is not taking time to look at the bottom of the page. But just "pre-release" would also work for me.

**Comment by deoren** [comment]
@rgerhards Alright. I was thinking about this some last night and it's probably a good idea to support multiple formats for the release string, but determine which one is used by a flag of some sort. For example, I still wish to see the longer, more verbose build string prominently in the docs that I build because it helps me quickly differentiate one build from another when I'm reviewing/proofing them. 

I do however agree that it is simply *too* long for use on the main site when using the `better` theme. With the `classic` theme that was used previously I felt it was "OK" (not wonderful, but OK) because it was placed in the upper-left corner when viewed on a PC and didn't take up much space.

I'll try to work on this later today to implement the shorter `rsyslog 8.x.x-pre docs` as the default build string.

**Comment by deoren** [comment]
> @rgerhards: more or less for my own ref, this is also an issue on the PC if looked at closely:
>
> http://www.rsyslog.com/doc/master/installation/install_from_source.html

Definitely. Compared to what we had before (speaking strictly of viewing it on a PC with browser) the build string dominates the top of the docs. Previously it was there, but almost "tucked away" out of the main view.

Ref: http://rsyslog.whyaskwhy.org/master/

## Before

![docs_web_browser_classic_theme](https://user-images.githubusercontent.com/1550338/35779625-f5d90b60-0995-11e8-8bbd-38c522f3fa0e.png)

## After

![docs_web_browser_better_theme](https://user-images.githubusercontent.com/1550338/35779624-f5cf460c-0995-11e8-947a-aad6abe0ed06.png)

**Comment by davidelang** [comment]
On Sun, 4 Feb 2018, Rainer Gerhards wrote:

>> Yet another option is to setup the release string shown prominently in the docs this way:
>>
>> -rsyslog 8.33-master-20180203-8d3b5a6 documentation
>> +rsyslog pre-release docs
>> and then retain the dev build release string that I added to the main index page not all that long ago
>
> I think this is an excellent idea, but would prefer a slight change in the name. How about
> ```
> -rsyslog 8.33-master-20180203-8d3b5a6 documentation
> +rsyslog 8.33-pre docs
> ```
> That's very short, but still conveys a good idea of which version it is close to (even if someone is not taking time to look at the bottom of the page. But just "pre-release" would also work for me.

I think '-master' would be the first thing to go :-) I really like having the 
commit in there, and either the date or some indication of how many commits past 
the tag we are (as git describe does)

git 8.33-pre is wrong, this isn't something prior to 8.33, it's 8.34-pre if 
anything (and there are a lot of possible commits that it could be)

David Lang

**Comment by deoren** [comment]
What if we drop the version number entirely? 

Perhaps go with something like `rsyslog pre-release docs`  or `rsyslog in-dev docs` ?

**Comment by davidelang** [comment]
On Mon, 5 Feb 2018, Deoren Moor wrote:

> What if we drop the version number entirely?
>
> Perhaps go with something like `rsyslog pre-release docs`  or `rsyslog in-dev docs` ?

put in the date or commit so that if you have a few copies around you have at 
least a rough idea what's what.

for docs, that probably makes more sense than the version of rsyslog at the time 
you are working on the docs (since most of the doc work is really independent of 
the development of new features)

**Comment by deoren** [comment]
> @davidelang: 
> put in the date or commit so that if you have a few copies around you have at
> least a rough idea what's what.

For the title specifically or just somewhere on the main page? I like having it in the title myself (and plan to have a cron build script generate the longer titles for my own builds), but as I understand it the current theme choice limits the title length.

How does `rsyslog 8d3b5a6 docs` or `rsyslog in-dev 8d3b5a6 docs` look?

> for docs, that probably makes more sense than the version of rsyslog at the time
> you are working on the docs (since most of the doc work is really independent of
> the development of new features)

For the most part I'd say that you are right, but we've begun targeting milestones with doc updates to have a general idea of when the changes would land on the stable branch. I do tend to think of them as separate however (as you say), especially for much of the cleanup work which is most version independent.

**Comment by rgerhards** [comment]
> git 8.33-pre is wrong, this isn't something prior to 8.33, it's 8.34-pre if
> anything (and there are a lot of possible commits that it could be)

No, we use the same scheme currently that the main project uses. After release, we bump the version number (and add .master in git) and next release we remove (.master). So it really is
```
8.32.0 < 8.33_pre < 8.33.0 [< 8.34_pre < 8.34.0 < ...]
```
or, in git versions used
```
8.32.0 < 8.33.0.master < 8.33.0
```

**Comment by rgerhards** [comment]
> for docs, that probably makes more sense than the version of rsyslog at the time
> you are working on the docs (since most of the doc work is really independent of
> the development of new features)

IMHO it makes sense to use the version in the doc as well, as I try hard to add doc at the same time I add features, so if you use 8.33 together with 8.30 doc you sometimes has a problem and vice versa.

That said, for the daily build master branch I am actually happy with anything that doesn't clutter the screen too much, let's say with a max size of 16 (preferred) to 20 chars.

**Comment by davidelang** [comment]
On Sun, 4 Feb 2018, Deoren Moor wrote:

>> @davidelang:
>> put in the date or commit so that if you have a few copies around you have at
>> least a rough idea what's what.
>
> For the title specifically or just somewhere on the main page? I like having it in the title myself (and plan to have a cron build script generate the longer titles for my own builds), but as I understand it the current theme choice limits the title length.
>
> How does `rsyslog 8d3b5a6 docs` or `rsyslog in-dev 8d3b5a6 docs` look?

looks good to me, let's see what rainer thinks

**Comment by rgerhards** [comment]
```rsyslog 8d3b5a6 docs``` it's OK with me. It sufficiently short (20 chars) and conveys the idea that it is a pre-release. Previously we had "master" instead of the git hash, so we get some extra bit of information without going more verbose. Works for me :-)

**Comment by deoren** [comment]
> @rgerhards: rsyslog 8d3b5a6 docs it's OK with me. It sufficiently short (20 chars) and conveys the idea that it is a pre-release. Previously we had "master" instead of the git hash, so we get some extra bit of information without going more verbose. Works for me :-)

I'll work on getting that done. I had originally planned to have something today, but with issues at work I didn't have the time today I thought I would.

**Comment by deoren** [comment]
It will take some time to build (I have a lot of dead branches to prune from my fork), but the proposed change should be visible here in the next 30 minutes:

http://rsyslog.whyaskwhy.org/i537-short-dev-build-release-string/
