### ISSUE TITLE
imuxsock: What is the maximum burst limit / interval limit possible?

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#541]
Need to update the imuxsock doc with that info.

refs: https://kb.monitorware.com/topic13150.html

**Comment by rgerhards** [comment]
I need to check, but it is very high. probably 2^31. so for practical reasons, there is no limit (99% sure)

**Comment by deoren** [comment]
@rgerhards 

Thanks. Once you have a chance to confirm (no rush), I'll be happy to update the docs to reflect that value.

**Comment by rgerhards** [comment]
I checked. In theory it depends on data type. The burst counter is an ```unsigned short``` which in theory could mean 16 bits and (2^16)-1 the highest value. In practice, though it is 32 bit. But the function that picks up the value from the config uses an ```int```. So in practice the highest value is (2^31)-1 and so what I said.

I guess the real description is "the value be as high as any practical need" - the limit IMHO is of total irrelevance in practice.
