### ISSUE TITLE
Clarify whether evaluation of the backtick string format happens only at startup

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#544]
See https://github.com/rsyslog/rsyslog-doc/pull/512#issuecomment-363334844

**Comment by rgerhards** [comment]
Just in case giving quick answer here: these are *constant* string, so yes, this is only once (on startup).

BTW: this is the diff between dev and end user thinking. For me all is crystal clear when I say it's a constant string. How else could it be modified ;-)

**Comment by deoren** [comment]
> @rgerhards: BTW: this is the diff between dev and end user thinking. For me all is crystal clear when I say it's a constant string. How else could it be modified ;-)

Maybe. I didn't initially think much of the lack of clarification, perhaps because I saw you mention elsewhere that it is set at startup and had that in mind when I reviewed the content. Either way, this may be a case of it being better to be explicit than implicit (I'm very much guilty of this).

I should be able to make time to add this note to the docs sometime today.
