### ISSUE TITLE
Improve Rainerscript function documentation

### ISSUE THREAD

**Issue by PascalWithopf** [rsyslog/rsyslog-doc#634]
Refers to https://www.rsyslog.com/doc/v8-stable/rainerscript/functions.html

At the moment this documentation consists of one page with a long list of all available functions. When there were not many functions this was not a problem, but as this list has grown and more complicated functions are available the list has gotten unclear.
@rgerhards had the idea to create a page for every function.

Then we would have a clear list of all functions on the referred page and every function had its own page with a description and examples.

**Comment by PascalWithopf** [comment]
Any thoughts on this @deoren ?

**Comment by deoren** [comment]
> @PascalWithopf: @rgerhards had the idea to create a page for every function.
> ...
> Any thoughts on this @deoren ?

Thanks for asking.

I think the pros outweigh any negatives in this case. It may feel an odd choice to start with, but it would make it a lot easier to add in examples and other related content specific to the function over time. If we attempt that with the current page we'll quickly create a large "wall of text" that becomes harder to navigate.

One of the things we can do is when finished, we end up with a similar effect that we get now with this index page:

https://www.rsyslog.com/doc/v8-stable/rainerscript/index.html

Looking there, you can easily spot and jump right to the desired function. If we keep the functions exposed in a similar manner I think we'll be good.

**Comment by deoren** [comment]
> @davidelang: It doesn't have to be one function per page (sometimes related functions can and
should share a page), but each function on the main page should be a link to the
appropriate detail page.

I thought about that, but wasn't sure how to suggest that the functions be grouped. I imagine for some there will be a logical fit, but for others maybe not so much. Perhaps for those they could go under a general/misc heading? I dunno.

I'll try to take another look at the list of functions and see what groupings appear natural.

**Comment by davidelang** [comment]
On Sun, 25 Mar 2018, Deoren Moor wrote:

>> @davidelang: It doesn't have to be one function per page (sometimes related functions can and
> should share a page), but each function on the main page should be a link to the
> appropriate detail page.
>
> I thought about that, but wasn't sure how to suggest that the functions be grouped. I imagine for some there will be a logical fit, but for others maybe not so much. Perhaps for those they could go under a general/misc heading? I dunno.

I wouldn't worry too much about grouping them.

On the 'main' page you can start with an alphabetical ordered list, then as you 
go through the list making each one into a link, if it seems like a function is 
explained best in conjuction with another function, put them on the same 
secondary page, if there isn't an obvious combination that jumps out, make it be 
a page on it's own.

> I'll try to take another look at the list of functions and see what groupings appear natural.

A second page that lists functions in groups would be very helpful, and I 
suspect after going through the excercise above, there will be some obvious 
groupings. But to start with, just work with a full alphabetical list.

**Comment by deoren** [comment]
@davidelang ACK.

@PascalWithopf

I've had some unexpected stuff come up with work, so won't be able to look at this for a bit. Everything that @davidelang has said thus far makes sense, but I would try to find a way to do this so that we don't find ourselves maintaining a list manually. If done the way the module pages are handled, the list will build itself by having the functions as separate files with good titles for the separate pages.

For example, this page:

https://raw.githubusercontent.com/rsyslog/rsyslog-doc/master/source/configuration/modules/idx_input.rst

results in this:

http://www.rsyslog.com/doc/v8-stable/configuration/modules/idx_input.html

**Comment by PascalWithopf** [comment]
I don't know if I understand this correct.

You want a main page with a list of all functions, which link to a second page where the function documentations are written? Or do you want multiple pages with groups of functions?

I will make a commit splitting the function documentations on different pages and then we can see further on how to group them and other topics.
