### ISSUE TITLE
parser.permitSlashInHostname and parser.permitSlashInProgramName

### ISSUE THREAD

**Issue by lennardk** [rsyslog/rsyslog-doc#639]
source/configuration/properties.rst [1] mentions the existance of both parser.permitSlashInHostname and parser.permitSlashInProgramName.
It is my belief that the former does not actually exist. Both descriptions seem to relate to programname (and not hostname). I think permitSlashInHostname was simply a misspelling of permitSlashInProgramName in e80b64fd1121bd0c0eb4d7725794204f36a3f895 and the doc for permitSlashInHostname itself was added later because it appeared to be missing.

[1] https://github.com/rsyslog/rsyslog-doc/blob/master/source/rainerscript/global.rst

**Comment by deoren** [comment]
Thanks for opening this issue, we will take a closer look at this.

**Comment by deoren** [comment]
@lennardk I'm still learning the ins/outs of rsyslog (probably will be for years), and so I thought at first you were right. I looked through the source project (case-insensitive search) and turned up multiple hits for `permitSlashInProgramName` in `runtime/glbl.h`, `runtime/glbl.c` and `runtime/msg.c`, but nothing for `permitSlashInHostname`. I then got a hit for `permitSlashInHostname` in `tools/pmrfc3164.c`.

See https://github.com/rsyslog/rsyslog/blob/c325b096e95f5b7de54b6d087fb41d437f611624/tools/pmrfc3164.c#L67 for what I'm referring to. Based on the usage there, I think both parameters are correct, but will defer to others to confirm for sure.

**Comment by deoren** [comment]
@rgerhards I assume I'm right in that both parameters are fully supported?

**Comment by lennardk** [comment]
@deoren well... almost.

You got a hit on slash****es****inhostname, not slashinhostname. Also, I believe while permit.slashesinhostname exists, it is not a global and can only be specified when explicitly using pmrfc3164.
As such, it is documented at https://github.com/rsyslog/rsyslog-doc/blob/master/source/configuration/modules/pmrfc3164.rst and probably doesn't belong in global.rst.

```
root@rsyslog:/tmp/rsyslog# for x in *; do cat $x; rsyslogd -f $x -N9; done
```
```
+ for x in *
+ cat parser-slash.conf
parser(name="rfc3164.slash"
      type="pmrfc3164"
      permit.slashinhostname="on")
+ rsyslogd -f parser-slash.conf -N9
rsyslogd: version 8.32.0, config validation run (level 9), master config parser-slash.conf
rsyslogd: error during parsing file parser-slash.conf, on or before line 3: parameter 'permit.slashinhostname' not known -- typo in config file? [v8.32.0 try http://www.rsyslog.com/e/2207 ]
rsyslogd: CONFIG ERROR: there are no active actions configured. Inputs will run, but no output whatsoever is created. [v8.32.0 try http://www.rsyslog.com/e/2103 ]
```
```
+ for x in *
+ cat parser-slashes.conf
parser(name="rfc3164.slash"
      type="pmrfc3164"
      permit.slashesinhostname="on")
+ rsyslogd -f parser-slashes.conf -N9
rsyslogd: version 8.32.0, config validation run (level 9), master config parser-slashes.conf
rsyslogd: CONFIG ERROR: there are no active actions configured. Inputs will run, but no output whatsoever is created. [v8.32.0 try http://www.rsyslog.com/e/2103 ]
```
```
+ for x in *
+ cat slash.conf
global(permit.slashinhostname="on")
+ rsyslogd -f slash.conf -N9
rsyslogd: version 8.32.0, config validation run (level 9), master config slash.conf
rsyslogd: error during parsing file slash.conf, on or before line 1: parameter 'permit.slashinhostname' not known -- typo in config file? [v8.32.0 try http://www.rsyslog.com/e/2207 ]
rsyslogd: CONFIG ERROR: there are no active actions configured. Inputs will run, but no output whatsoever is created. [v8.32.0 try http://www.rsyslog.com/e/2103 ]
```
```
+ for x in *
+ cat slashes.conf
global(permit.slashesinhostname="on")
+ rsyslogd -f slashes.conf -N9
rsyslogd: version 8.32.0, config validation run (level 9), master config slashes.conf
rsyslogd: error during parsing file slashes.conf, on or before line 1: parameter 'permit.slashesinhostname' not known -- typo in config file? [v8.32.0 try http://www.rsyslog.com/e/2207 ]
rsyslogd: CONFIG ERROR: there are no active actions configured. Inputs will run, but no output whatsoever is created. [v8.32.0 try http://www.rsyslog.com/e/2103 ]
```

**Comment by deoren** [comment]
> @lennardk: 
>
> @deoren well... almost.
> 
> You got a hit on slashesinhostname, not slashinhostname. Also, I believe while permit.slashesinhostname exists, it is not a global and can only be specified when explicitly using pmrfc3164.
> As such, it is documented at https://github.com/rsyslog/rsyslog-doc/blob/master/source/configuration/modules/pmrfc3164.rst and probably doesn't belong in global.rst.

Good catch (thank you for the diplomatic correction), poor attention to detail on my part. That is what I get for quickly reviewing a new report. 

Looking over the specific commit you referenced, I concur that it looks like the events played out as you say. The fix appears to be to remove the references to the non-existent global parameter. I don't have time to make the change myself tonight, but should be able to tackle this soon if nobody beats me to it with another PR.
