### ISSUE TITLE
multi-threaded action queues

### ISSUE THREAD

**Issue by n2N8Z** [rsyslog/rsyslog-doc#655]
https://github.com/rsyslog/rsyslog-doc/blob/master/source/concepts/queues.rst
"For example, in current output module design, actions do not support multi-threading. Consequently, the number of worker threads is fixed to one for action queues and can not be changed."

This seems to be contradicted by: http://blog.gerhards.net/2013/06/rsyslog-performance-main-and-action.html
"multiple threads on action queues can build string concurrently"
"it is hard to envision that more than two action queue worker threads can make much sense."

And this: https://www.rsyslog.com/performance-tuning-elasticsearch/
"one or more action queue threads takes properties from events according to templates"

**Comment by rgerhards** [comment]
the first one is outdated. A PR to fix it would be appreciated.

**Comment by rgerhards** [comment]
sry, accidently closed (wrong button clicked ;-))

**Comment by n2N8Z** [comment]
Sorry, I don't think I understand the architecture well enough to be able to make the corrections.

I would be good if the article could be flagged as out of date though, so that other users aren't mislead, since that page seems to be linked to from various other pages.
