### ISSUE TITLE
Where is the "abort" option specified for oversizemode?

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-doc#669]
@rgerhards @PascalWithopf 

I see this error message mentioned on rsyslog/rsyslog#2712:

```
imrelp: librelp too old, oversizemode defaults to "abort" [v8.35.0 try http://www.rsyslog.com/e/2186 ]
```

Where can the "abort" mode be specified?

AFAIK, the existing [master doc](https://www.rsyslog.com/doc/master/rainerscript/global.html) (b4f6f377c6fc7f1a2e8c32d21550cae333d58cfa) doesn't include that option for the `oversizemsg.input.mode` parameter. Instead, just these options are listed:

- `truncate`
- `split`
- `accept`

Is the abort mode specified via a different parameter or does it just need to be included in the list and marked as the default?

**Comment by rgerhards** [comment]
It's an imrelp option, not a global one. It is here https://www.rsyslog.com/doc/v8-stable/configuration/modules/imrelp.html but as it looks could need some love re the formatting ;-)

@PascalWithopf could you fix that?

**Comment by PascalWithopf** [comment]
@rgerhards @deoren oversizemsg.input.mode is a global parameter.

Imrelp has another parameter named "oversizeMode". Both parameters are documented.

**Comment by PascalWithopf** [comment]
Imrelp parameter oversizeMode is dependent on the librelp version and defines only the mode that librelp uses
The global parameter oversizemsg.input.mode specifies the mode for rsyslog.

**Comment by deoren** [comment]
> @rgerhards: It's an imrelp option, not a global one.

Ah; sorry, I completely missed that. Thanks for pointing me in the right direction.

> @PascalWithopf: Imrelp parameter oversizeMode is dependent on the librelp version and defines only the mode that librelp uses
> The global parameter oversizemsg.input.mode specifies the mode for rsyslog.

Thanks for emphasizing that, I'll try to keep those straight in my mind.
