### ISSUE TITLE
Queue size documentation unclear

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog-doc#718]
In [Limiting the Queue Size](https://github.com/rsyslog/rsyslog-doc/blob/d43d0a9ed4f914fd89917025e1c5a91ae27e5ba7/source/concepts/queues.rst#limiting-the-queue-size) section it states that:

> All queues, including disk queues, have a limit of the number of elements they can enqueue. 

While the paragraph right after begins with:

> Disk assisted queues are special in that they do **not** have any size limit. 

This is quite confusing for user, my understanding is that the first paragraph should state exception for DA queues, but wanted to make sure before starting with PR.

**Comment by jvymazal** [comment]
@rgerhards ideas please?

**Comment by rgerhards** [comment]
They do not have a limit on the number of messages, but you can specify a file size limit, which then applies.

**Comment by jvymazal** [comment]
Ok, one more question regarding this: the doc specifies "_$<object>QueueMaxFileSize_" config directive. Is there any new syntax alternative to this?
Thank.

**Comment by rgerhards** [comment]
I think this is actually not the right old-style directive (it's just the split for one file, not the total permitted), but that really doesn't matter. The current one is ```queue.maxdiskspace``` - see https://www.rsyslog.com/doc/master/rainerscript/queue_parameters.html

```queue.maxfilesize``` I think corresponds to what you have named. And seeing this, it indeed looks like some more content on the current page wouldn't be bad ;-)

**Comment by rgerhards** [comment]
One more: https://www.rsyslog.com/doc/v8-stable/concepts/queues.html has the queue parameters (unfortunately only the obsolete ones) and how they relate.  Check for "Limiting the Queue Size".

@PascalWithopf  would you like/have time to update the doc to current style?

**Comment by jvymazal** [comment]
Also, note that the [concepts](https://github.com/rsyslog/rsyslog-doc/blob/d43d0a9ed4f914fd89917025e1c5a91ae27e5ba7/source/concepts/queues.rst#limiting-the-queue-size ) page specifies the default chunk size to 10Mb, while currently it is 1Mb - https://github.com/rsyslog/rsyslog/blob/670d6661ecb7c1d69b3453f5d674189d2e90af27/runtime/queue.c#L1431
