### ISSUE TITLE
immark not yet documented

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog-doc#76]
The `immark` module is not yet documented. When you start with the new syntax you have to read the source code to find the `Interval` parameter.

**Comment by atc0005** [comment]
Relevant lines (AFAIK):

```c
/* defines */
#define DEFAULT_MARK_PERIOD (20 * 60)
```

I assume this means 20 minutes?

Refs:

- https://github.com/rsyslog/rsyslog/blob/master/plugins/immark/immark.c
- https://github.com/rsyslog/rsyslog/blob/e5e0918186c1335ef48fe4c498e8ee09ab82b21d/plugins/immark/immark.c#L52

**Comment by rgerhards** [comment]
> I assume this means 20 minutes?

yes
