### ISSUE TITLE
How to configure dnscacheEnableTTL

### ISSUE THREAD

**Issue by paride5745** [rsyslog/rsyslog-doc#863]
At the end of the issue rsyslog/rsyslog#1487 , it was said that `rsyslog` supports `dnscacheEnableTTL`. However, I cannot find any documentation about it, how to configure it. 
Can you please add some documentation and examples on how to use it?

**Comment by paride5745** [comment]
I suggest adding a parameter name in this page:
https://www.rsyslog.com/doc/v8-stable/rainerscript/global.html

To get the relationship between what's documented and what's coded I had to read the code, which might not be easy for some users.

**Comment by rgerhards** [comment]
@paride5745 thx  this is exactly what PR #864 does :-)
