### ISSUE TITLE
define cnum() behavior if the expression is not a numeric value

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog-doc#905]
### Expected behavior
cnum() output is defined in all cases
### Actual behavior
cnum() output is undefined if the expression is not a numerical value

define it as either returning 0 or that it stops parsing at the first non-numeric character, but define something

I know that it can vary based on implementation and you don't want to be locked in to the exact details of the current implementation, but I really had "undefined, we may chose to do anything and it's legit" (some programs do really odd things when they hit something technically undefined), so even 'is guaranteed to return 0 or some best effort number based on the input is better than "behavior is undefined"

**Comment by rgerhards** [comment]
preview doc: http://ubuntu16.rsyslog.com/doc/doc-2020-09-02-08-32-21-c672465/rainerscript/functions/rs-cnum.html?highlight=cnum (will be kept some days)
