### ISSUE TITLE
A directive $InputTCPSupportOctetCountedFraming has a typo in imtcp/imptcp document web page

### ISSUE THREAD

**Issue by standby24x7** [rsyslog/rsyslog-doc#920]
https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html

In SupportOctetCountedFraming,
obsolete legacy directive is called  $InputTCPSupportOctetCountedFraming
I think this one has a typo.
The correct directive nake should be : $InputTCP**Server**SupportOctetCountedFraming

In plugins/imtcp/imtcp.c
853         CHKiRet(regCfSysLineHdlr2(UCHAR_CONSTANT("inputtcp**server**supportoctetcountedframing"), 0, eCmdHdlrBinary,

If I configure the directive as  $InputTCPSupportOctetCountedFraming into rsyslog.conf
and  restart the rsyslogd, then rsyslogd complains such as
 
"rsyslogd-3003: invalid or yet-unknown config file command "InputTCPSupportCountedFraming" -
have you forgotten to load a module? 

Rsyslogd accepts $InputTCPServerSupportOctetCountedFraming.

The same typo exist in imptcp web page, too.
https://www.rsyslog.com/doc/v8-stable/configuration/modules/imptcp.html

Wrong: $InputPTCPSupportOctetCountedFraming
Correct: $InputPTCP**Server**SupportOctetCountedFraming

In plugins/imptcp/imptcp.c
2620         CHKiRet(omsdRegCFSLineHdlr(UCHAR_CONSTANT("inputptcp**server**supportoctetcountedframing"), 0, eCmdHdlrB     inary,

**Comment by rgerhards** [comment]
closed by #921
