### ISSUE TITLE
Why is "reopenOnTruncate" an experimental feature?

### ISSUE THREAD

**Issue by miztake** [rsyslog/rsyslog-doc#936]
imfile.rst stated the following:

>   reopenOnTruncate
>     This is an experimental feature that tells rsyslog to reopen input file when it was truncated (inode unchanged but file size on disk is less than current offset in memory).

Why is reopenOnTruncate an **experimental** feature?
For example, is it because reopenOnTruncate has many bugs?
When will the description of **experimental** be deleted?

**Comment by rgerhards** [comment]
Well, it will never become a regular feature, because it does not work reliably by the way of what it does. When it is activated, there is always as possibility of loss of data, albei we try to limit it. The whole idea of truncating a monitored file is flawed.
