### ISSUE TITLE
Update readthedocs pdf version

### ISSUE THREAD

**Issue by Ashlanfox** [rsyslog/rsyslog-doc#975]
Hi,

I just realised I was working with rsyslog's 2017 documentation version on [readthedocs ](https://rsyslog.readthedocs.io/), given the fact that I searched for it on google I didn't expect the top results to be that old. Any plan on updating readthedocs `master` branch (html and/or pdf) ?

Sorry if that has already been answered, but I couldn't find anything on repo.

**Comment by davidelang** [comment]
we have no influence on what readthedocs publishes. We host the most current 
documentation on rsyslog.com

David Lang

**Comment by Ashlanfox** [comment]
I wrongly thought this was maintained by M. Gerhards as his name was showcased on the readthedocs project page.

**Comment by davidelang** [comment]
readthedocs takes publicly available documentation and republishes it. The 
licenses of the documentation allows this, but the way they do it can mislead 
people into thinking that readthedocs is the up-to-date officially maintained 
version of the docs.

it's convienient to have docs for so much in one place, it would be much nicer 
if they automated updates to the docs once they start hosting them to keep them 
updated.

David Lang

**Comment by Ashlanfox** [comment]
I'm writing my thesis which involves rsyslog and having a single manual/document containing all specifications is really convenient for referencing (I can cite specific page and paragraph). I will manually build the documentation then. Thanks again for your insights.

**Comment by Ashlanfox** [comment]
> readthedocs takes publicly available documentation and republishes it. The licenses of the documentation allows this, but the way they do it can mislead people into thinking that readthedocs is the up-to-date officially maintained version of the docs. it's convienient to have docs for so much in one place, it would be much nicer if they automated updates to the docs once they start hosting them to keep them updated. David Lang
> […](#)
> On Thu, 28 Jul 2022, Ashlanfox wrote: I wrongly thought this was maintained by M. Gerhards as his name was showcased on the readthedocs project page.

I have emailed them and apparently this is not maintained by them:
![image](https://user-images.githubusercontent.com/20969704/181630005-7561547e-495a-4335-ac0e-8dd47e711d76.png)

**Comment by rgerhards** [comment]
Readthedocs folks are irresponsible and only interested in driving profit from impersonating as valid OSS projects. We tried several times to take over the abandoned project over there and they never were finally willing to hand it over. Google should block these du*""cks.

**Comment by rgerhards** [comment]
Btw: this is the standard answer you get.
